src/caffelib.cc

Support for ELU, using PR https://github.com/BVLC/caffe/pull/3388
In API, use `activation:"elu"` and `elu_alpha` to specify the value of the saturation control variable `alpha`.
Original paper:
Clevert, D.-A., Unterthiner, T., & Hochreiter, S. (2015). Fast and Accurate Deep Network Learning by Exponential Linear Units (ELUs). http://arxiv.org/abs/1511.07289

added support for ELU activation units with Caffe

---

templates/caffe/resnet_101/deploy.prototxt
templates/caffe/resnet_101/resnet_101.prototxt
templates/caffe/resnet_101/resnet_101_solver.prototxt
templates/caffe/resnet_152/deploy.prototxt
templates/caffe/resnet_152/resnet_152.prototxt
templates/caffe/resnet_152/resnet_152_solver.prototxt
templates/caffe/resnet_18/deploy.prototxt
templates/caffe/resnet_18/resnet_18.prototxt
templates/caffe/resnet_18/resnet_18_solver.prototxt
templates/caffe/resnet_32/deploy.prototxt
templates/caffe/resnet_32/resnet_32.prototxt
templates/caffe/resnet_32/resnet_32_solver.prototxt
templates/caffe/resnet_50/deploy.prototxt
templates/caffe/resnet_50/resnet_50.prototxt
templates/caffe/resnet_50/resnet_50_solver.prototxt

This is support for the state-of-the-art nets just released by https://github.com/KaimingHe/deep-residual-networks. They are implemented as DeepDetect neural net templates: `resnet_50`,`resnet_101` and `resnet_152` are now available from the API.
**Note: training successfully tested on `resnet_18` and `resnet_50`**
For using the nets in `predict` mode:
- model repository preparation:
* download models from https://github.com/KaimingHe/deep-residual-networks
* `mkdir path/to/model`
* `cp ResNet-50-model.caffemodel path/to/model/`
* `cp ResNet_mean.binaryproto path/to/model/mean.binaryproto`
- service creation:
```
curl -X PUT "http://localhost:8080/services/imageserv" -d "{\"mllib\":\"caffe\",\"description\":\"image classification …
```

Support for Deep Residual Net (ResNet) reference models for ILSVRC

---

src/apidata.cc
src/apidata.h
src/supervisedoutputconnector.h
src/unsupervisedoutputconnector.h

This is the binarized output for #56. It allows creating binary hash codes out of deep neural net layer weights. 
This PR paves the way toward straightforward image similarity search and other related applications.

binarized unsupervised output with 'binarized' boolean API parameter

---

src/caffeinputconns.h
src/caffelib.cc
src/caffemodel.cc
src/caffemodel.h
src/imginputfileconn.h
src/jsonapi.cc
src/txtinputfileconn.cc
tests/ut-caffeapi.cc

This PR allows the `POST /predict` call to return accuracy `measure` (see [output connectors API](http://www.deepdetect.com/api/?shell#output-connectors)).
This is useful now for testing an already trained model, and later on for ensembling.
Example call:
- create text service from already trained model (as created following http://www.deepdetect.com/tutorials/txt-training/):
```
curl -X PUT "http://localhost:8080/services/n20" -d "{\"mllib\":\"caffe\",\"description\":\"newsgroup classification service\",\"type\":\"supervised\",\"parameters\":{\"input\":{\"connector\":\"txt\"},\"mllib\":{\"nclasses\":20}},\"model\":{\"repository\":\"/path/to/models/n20\"}}"
```
- test call with `predict` resource:
```
curl -X POST 'http://localhost:8080/predict' -d …
```

Support for labeled data on POST /predict call

---

src/caffelib.cc

GPU memory overload with Caffe appears to be eratically recoverable. 
This PR makes the recovery deterministically possible. However it is obversed that multiple predict calls within memory bounds are often necessary for the service to recover after a GPU memory overflow.
For instance, on a 4GB using `resnet_152`, passing more than 7 or 8 images leads to 
```
{"status":{"code":500,"msg":"InternalError","dd_code":1007,"dd_msg":"src/caffe/util/im2col.cu:61 / Check failed (custom): (error) == (cudaSuccess)"}}
```
In our tests, trying a few more `predict` calls on the same service, with less images per batch, unlocks the memory and allows for the service to proceed correctly.
Note that deleting the service, re-creating it, and passing less images on the first `predict` call does not appear to …

Recovery from Caffe GPU memory overload on net prediction

---

CMakeLists.txt
README.md
src/CMakeLists.txt
src/caffeinputconns.cc
src/caffeinputconns.h
src/caffelib.cc
src/caffelib.h
src/csvinputfileconn.h
src/jsonapi.cc
src/services.h
src/svminputfileconn.cc
src/svminputfileconn.h
src/txtinputfileconn.cc
src/txtinputfileconn.h
templates/caffe/lregression/lregression_solver.prototxt
tests/ut-caffe-mlp.cc
tests/ut-caffeapi.cc

Neural embeddings have proved useful for a variety of tasks, such as text classification. However, sparse representations such as one-hot vectors or bag of words (BOW) still yield better results in practice on a series of datasets. This has been carefully measured in practice by one of our partners and ourselves as well.
This PR brings support for sparse representation and computation, for CPU and GPU, to be used with the text input connectors, and other forthcoming connectors (see #112).
Sparse computations are realized by a custom version of Caffe, available from https://github.com/beniz/caffe/tree/master_dd_integ_sparse, more details in #8.
Current status:
Example:
Use `sparse:true` parameter to input `connector`.
This PR is sponsored by [ioSquare](http://iosquare.com/).

Support for sparse computations and sparse neural network layers with (custom) Caffe

---

CMakeLists.txt
src/caffeinputconns.h
src/caffelib.cc
src/caffelib.h
src/csvinputfileconn.cc
src/csvinputfileconn.h
src/supervisedoutputconnector.h

This is an early release of basic autoencoder support with a few options.
This PR contains:
- basic autoencoder via `SigmoidCrossEntropyLoss`
- support for API `autoencoder` boolean parameter for both `mllib` and input CSV`connector`
- training + prediction via API
- ability to control the layers initialization via `init` and `init_std` like `gaussian` and `xavier`, with application beyond autoencoders
- a full working example in comments below for now
Known caveats:
- autoencoder is a `supervised` method and trains with `supervised` API parameter. This choice can be discussed but most practitioners would agree that autoencoders are at best semi-supervised techniques
- autoencoder trains as `supervised` but requires `unsupervised` service creation to access the prediction at layer level …

Autoencoder support via API + Caffe from CSV data

---

src/caffeinputconns.cc
src/caffeinputconns.h
src/caffelib.cc

This PR brings the ability to `POST /predict` to size the batches according to `mllib.net.test_batch_size`. This means that `predict` now supports running over more data than there's memory available for either in RAM or on GPU.
Note that the batch size must still be specified via `test_batch_size` and it must be such that data fit the available memory for this batch size.
Examples of predicting over 3 images with `test_batch_size` of 2:
```
curl -X POST 'http://localhost:8080/predict' -d '{"service":"places","parameters":{"input":{"width":224,"height":224},"mllib":{"net":{"test_batch_size":2}},"output":{"best":3}},"data":["http://www.orelle.net/images/fr/station-orelle-montagne-savoie-ete.jpg","http://www.tortugamundi-voyages.com/wp-content/uploads/2012/03/Haute_Falaise_3-062-Copier.jpg", …
```

Prediction auto-sizing of batches, ref #129

---

src/supervisedoutputconnector.h
tests/ut-conn.cc

Support for MCC, see https://en.wikipedia.org/wiki/Matthews_correlation_coefficient
Usages:
* binary classes problems
* use `mcc` in `measures` in API
Advantages:
* robust when classes are highly imbalanced
* can be used as test accuracy along `auc` and `f1

Support for Matthews correlation coefficient for binary classes problems

---

CMakeLists.txt
cmake/Cuda.cmake
main/CMakeLists.txt
src/caffelib.cc
src/caffelib.h
tests/CMakeLists.txt

This PR adds support for multiple GPUs with Caffe as requested by #179.
The following range of API `gpuid` parameter types and values are supported:
- single value, e.g. `gpuid:0` or `gpuid:1`
- special `gpuid:-1` value to specify that all GPUs should be used
- any combination in an array, e.g. `gpuid:[1,3]` to use two GPUs among many for instance

adding support for multiple GPUs for Caffe via API, ref #179

---

CMakeLists.txt
src/caffeinputconns.cc
src/caffeinputconns.h
src/caffelib.cc
src/caffelib.h

Related to completion of #202.
Usage:
- in `POST /train` calls, use `class_weights:[1.0,0.1,...]` as an array of floats, within the `mllib` object.

Added support for `class_weights` and special Softmax loss class for Caffe with weights

---

CMakeLists.txt
demo/objdetect/README.md
demo/objdetect/dd_client.py
demo/objdetect/objdetect.py
src/caffeinputconns.h
src/caffelib.cc
src/imginputfileconn.h
src/supervisedoutputconnector.h
templates/caffe/ssd_300/deploy.prototxt

This PR adds support for the image detection task (e.g. object detection) via [SSD](https://github.com/weiliu89/caffe/tree/ssd). Only prediction mode is covered by the present PR. Training should follow in a near futur.
Functionalities:
- multi-class object detection
- single and batch forward processing of images
- JSON output with bouding boxes resized to fit the originally submitted image
- threshold on prediction confidence via `confidence_threshold` output parameter
- ready-to use demo in [`demo/objdetect`](https://github.com/beniz/deepdetect/tree/ssd/demo/objdetect)
Sample usage:
- create service
This is identical to other tasks
```
curl -X PUT "http://localhost:8080/services/imageserv" -d "{\"mllib\":\"caffe\",\"description\":\"image classification …
```

SSD: Single Shot MultiBox Detector for prediction with DD

---

src/caffelib.cc
src/caffelib.h

FLOPS and number of parameters are reported in the server logs. Next to be reported by the API.
Example on a `ResNet 50`:
```
I0214 17:58:42.416816 21937 caffelib.cc:2658] Net total flops=3858026368 / total params=25556032
```
i.e. 3.85B FLOPS and 25.5M parameters.

Reporting net's flops and number of parameters for Caffe models

---

src/xgbinputconns.cc
src/xgblib.cc

XGBoost model feature map is typically useful when analyzing feature importance.

added automated creation of XGB feature map file 'model.fmap' when training from CSV

---

src/caffelib.cc

`ft_oldname` is used to update layers after.
```
// update relations from other layers
for (int l=net_param.layer_size()-1;l>k;l--)
{
caffe::LayerParameter *lparam = net_param.mutable_layer(l);
if (lparam->top(0) == ft_oldname)
lparam->set_top(0,ft_lname);
if (lparam->bottom(0) == ft_oldname)
lparam->set_bottom(0,ft_lname);
}
```
However when the layer of the name is different than the first top the condition `if (lparam->bottom(0) == ft_oldname)` will never trigger. This small PR corrects that by using the first top name instead of the layer name.

Finetuning - using feature top name instead of top name

---

src/svminputfileconn.h

The maximum number of features (in LMDB) is obtained by taking the max_id of the SVM. However, as the SVM files contain the id 0 we should append the maximum number of features by 1.
Let us take a SVM with the `max_id` is equal to 1000. That means that he has 1001 indices. However when a training is launched we observed that the size of the dimension `channels` is equal to 1000 and not 1001.

SVM connector - appending 1 to the max number of features

---

src/caffeinputconns.h
templates/caffe/vdcnn_9/deploy.prototxt
templates/caffe/vdcnn_9/vdcnn_9.prototxt
templates/caffe/vdcnn_9/vdcnn_9_solver.prototxt

VDCNN with 9 layers from https://arxiv.org/abs/1606.01781
* Service creation
```
curl -X PUT 'http://localhost:8100/services/agnews' -d '{"mllib":"caffe","description":"agnews classifier","type":"supervised","parameters":{"input":{"connector":"txt","characters":true,"embedding":true,"sequence":1014},"mllib":{"nclasses":4,"template":"vdcnn_9"}},"model":{"templates":"../../templates/caffe/","repository":"/path/to/model/"}}'
```
* Training
```
curl -X POST 'http://localhost:8100/train' -d '{"service":"agnews","parameters":{"input":{"connector":"txt","embedding":true,"sentences":true,"db":true,"test_split":0.06,"shuffle":true},"mllib":{"gpu":true,"net":{"batch_size":128,"test_batch_size":128},"solver":{"test_interval":1000,"snpashot":1000,"base_lr":0.01,"solver_type":"ADAM","iterations":25000} …
```

VDCNN template for text classification

---

src/svminputfileconn.cc

When doing aprediction on a SVM, indexes of SVM examples should be bounded. When and index is out of those bounds DD core dumps (see the #343)
This PR attempts to correct it by catching an error after reading an SVM line.
Basically it checks if after reading one line from SVM any value was added to the variable `vals`.
At this point in the code, if nothing was caught that means the SVM line seems correct however `vals` might be empty If the index is out of bounds (see line 96 of https://github.com/beniz/deepdetect/blob/master/src/svminputfileconn.cc). If the example has only indexes out of bounds `vals` will be empty and it makes DD core dumps. To avoid that, verifying if `vals` is not empty might be a solution.

Catch error when svm line is empty

---

docker/cpu-caffe-tf/Dockerfile
docker/gpu-caffe-tf/Dockerfile

I took the standard CPU and GPU Dockerfiles already provided and added my changes to build with both Caffe and TF backend libs. Since I don't use XGBoost myself and haven't tested the Dockerfiles with it included, I removed that.
The GPU versions build with the following NVIDIA configurations (Ubuntu 16.04, CUDA 8.0, cuDNN 5.1):
- GeForce GTX 1070 (driver 375.20), which I believe is compute capability 6.1
- GeForce GTX TITAN X (driver 375.26), which I believe is compute capability 5.2
This may need changes to be more generalized for other compute capabilities, etc.
Also note this is still affected by #230, #289.

Dockerfiles for CPU or GPU builds with Caffe+TF

---

templates/caffe/vdcnn_17/deploy.prototxt
templates/caffe/vdcnn_17/vdcnn_17.prototxt
templates/caffe/vdcnn_17/vdcnn_17_solver.prototxt

Add VDCNN with 17 layers from https://arxiv.org/abs/1606.01781
- Service creation
`curl -X PUT 'http://localhost:8100/services/agnews' -d '{"mllib":"caffe","description":"agnews classifier","type":"supervised","parameters":{"input":{"connector":"txt","characters":true,"embedding":true,"sequence":1014},"mllib":{"nclasses":4,"template":"vdcnn_17"}},"model":{"templates":"../../templates/caffe/","repository":"/path/to/model"}}'
`
- Training
`curl -X POST 'http://localhost:8100/train' -d '{"service":"agnews","parameters":{"input":{"connector":"txt","embedding":true,"sentences":true,"db":true,"test_split":0.06,"shuffle":true},"mllib":{"gpu":true,"net":{"batch_size":128,"test_batch_size":128},"solver":{"test_interval":1000,"snpashot":1000,"base_lr":0.01,"solver_type":"ADAM","iterations":25000}}," …

Add template for VDCNN with 17 layers

---

demo/segmentation/segment.py
src/caffelib.cc
src/unsupervisedoutputconnector.h

Output segmentation map is not interpolated (nearest neighbors) to fit the size of the input image. This eases usage and visualization from external applications.

Resized output segmentation labels + image size in output json

---

CMakeLists.txt
src/caffelib.cc
src/supervisedoutputconnector.h

Support for tasks such as:
- captcha reading
- speech to text
- machine translation
- image captioning
API update:
- `ctc:true` in `output` JSON object on `POST /predict`
- `blank_space:10` (or any other `int`, default to `-1`) to specify the CTC blank space index
Example:
- service creation
```
curl -X PUT "http://localhost:8080/services/ocr" -d '{
"mllib":"caffe",
"description":"OCR service",
"parameters":{
"input":{
"connector":"image"
},        
"mllib":{                             
"nclasses":11
}
},                                                                                                                            
"model":{
"repository":"/path/to/ctc_model/"
}
}'
```
- batch prediction
```
curl -X POST "http://localhost:8080/predict" -d '{ …
```

Support for inference with connectionist temporal classification (CTC) with caffe

---

src/caffelib.cc
src/mllibstrategy.h
src/mlservice.h

This implements #355.
Output variables are `remain_train` and `remain_train_str`.

JSON output now reports estimated remaining time of training jobs

---

src/mllibstrategy.h

If 'remain_time' is not obtained yet, DeepDetect throws an error and stops the training.
By doing this we do not calculate the estimated remaining time when we do not have this information

Fix calculation of estimated remain_time if remain_time is not available

---

src/supervisedoutputconnector.h
tests/ut-conn.cc

evacuate corner cases:
- some class never happens -> nan
- some class do not happen on one image -> bad normalization

Meaniou debug

---

main/dede.cc
src/httpjsonapi.cc
src/jsonapi.cc
src/jsonapi.h

This automates the creation of services when DD server starts.
File format is as follows:
- service creation:
```
service_create;sname;JSON string
```
where `sname` is the service name and the JSON is a string without external quotes
- service prediction
```
service_predict;JSON string
```

Services autostart via calls list in a file

---

src/httpjsonapi.cc

This eases Web app development.

Allow cross origin '*' returned by dd server (optional at server startup)

---

src/backends/caffe/caffelib.cc
src/backends/caffe/caffelib.h

New parameter is `scaling_temperature` a service creation ('PUT /predict').
This is to be used with our [libtscaling](https://github.com/jolibrain/libtscaling) for model automatic calibration.

Added support for softmax temperature scaling through API.

---

src/backends/caffe/caffeinputconns.h

When `mean.binaryproto` is available (e.g. model trained with DD), it is read as needed in order to remove the average pixel values from the input image. 
This PR fixes applying the mean when `mean.binaryproto` is not in the model repository and `mean` is defined in the `input` connector JSON object.

fixed mean subtraction to image when using Caffe model without mean.binaryproto

---

src/backends/caffe/caffelib.cc
src/backends/caffe/caffelib.h
tests/ut-caffe-mlp.cc

add api for dice losses 
- "loss":"dice"  
- "loss":"dice_binary" 
- "loss":"dice_binary_weighted"
in `mllib` (caffelib) parameters
WARNING: only dice is implemented in caffe atm

Dice loss api

---

src/supervisedoutputconnector.h

change aggregation of means
- the idea is to compute mean (over test images) of mean (over labels) of average precision (of bounding boxes)
- bug: the APs of one image (for every labels) were summed to previous mAP (supposedly over all images in test set) then divided by the number of labels in the current image, giving a weighted sum (the first map was divided n_test_images times, the second n_test_images -1 by the number of label of current image)
- Now the map is computed over one image (mean over labels) then summed to global mmap, and divided in the end by the number of image, so we have a mean mAP

correctly aggregate means

---

src/jsonapi.cc
src/jsonapi.h

This PR adds the ability to store a service creation file named `config.json` in the model directory. This file can later be used to re-create the service with the correct parameters.
API flag for file creation for `PUT /service` call is `store_config` in `output` parameter object (may change).

Config json file

---

src/backends/caffe/caffelib.cc
src/backends/caffe/caffelib.h
tests/ut-caffe-mlp.cc

works with new custom caffe
add ability tu use generalized dice (F1) loss for image segmentation, multilabel and optionally weighted
can be given an "ignore_label"
option to mllib:
```
"loss": "dice"
"loss": "dice_multiclass"
"loss": "dice_weighted"
```
this option, used with "template":"deeplab_vgg16" or "template":"unet" and "segmentation":true (input parameter) generates corresponding architectures with dice loss
mllib option ignore_label is also usable
-  service creation
```
curl -X PUT "http://localhost:8080/services/imageserv" -d '{
"mllib":"caffe",
"description":"image segmentation service",
"parameters":{
"input":{                              
"segmentation": true, "connector":"image", "db":false
},                                     
"mllib":{ …
```

generalized dice loss (for good)

---

src/mllibstrategy.h
src/mlservice.h
tests/ut-httpapi.cc

Added `max_hist_point` parameter as the maximum number of measured points to be returned. Full history is subsampled.

Measure history subsampling

---

.travis/install.sh

Travis builds use Ubuntu 14.04 and require cloning spdlog. Current up-to-date version seems to be breaking some elements, pinning it to last stable release 0.17.0.

Pinning spdlog to v0.17.0 for Travis

---

src/mllibstrategy.h
src/mlservice.h
tests/ut-httpapi.cc

At the moment, limiting the number of measure history points is only available by using the single parameter alone `parameters.output.max_hist_points=1000` (with any value) on a `GET /train` call. This automatically activates `parameters.output.measure_hist=true` that at the moment cannot be passed concurrently.

Fix to history subsampling.

---

src/supervisedoutputconnector.h

map_# measures where normalized correctly, but not put back into map used for output , due to a wrong 
map access through iterator

wrong map_# measures 

---

src/jsonapi.cc
src/jsonapi.h
src/mlservice.h

This PR automates the storage of full metric history after a training job has finished.
Related to #354 
`metrics.json` is the final file stored in model directory.

stores full metric history into metrics.json once training job has finished

---

src/mlservice.h

Let an external application know about a service's model directory location.

GET /train status call returns model directory

---

src/backends/caffe/caffelib.cc
src/backends/caffe/caffemodel.cc
src/backends/caffe/caffemodel.h

This PR allows copying from an existing model directory, locating the best weights, at service creation for Caffe backend.
Does not copy anything if the `best_model.txt` file cannot be found.

Ability to copy from an existing model repository at service creation

---

src/jsonapi.cc
src/mlservice.h

This saves `metrics.json` file upon every status call on a training job.

Store metrics on disk upon every status call

---

src/backends/caffe/caffeinputconns.cc
src/backends/caffe/caffemodel.cc
src/backends/caffe2/caffe2inputimg.cc
src/backends/caffe2/caffe2model.cc
src/backends/dlib/dlibmodel.cc
src/backends/tf/tfmodel.cc
src/backends/xgb/xgbmodel.cc
src/imginputfileconn.h
src/txtinputfileconn.cc
src/utils/fileops.hpp

In case of a large datasets it might be difficult to have several thousands of images in one folder. This PR makes it possible to have sub-directories in classes folder.
For instance for a binary classification on images with two labels *1* and *0*.
Now we can create sub-directories in those directories to have less  elements in folders.
Before the tree must be like the following
```
data
|-- 1
|   |-- image_1
|   |-- image_2
|   `-- etc.
|-- 0
|   |-- image_1
|   |-- image_2
|   `--  etc.
```
Now it's possible to have the following
```
data
|-- 1
|   |-- split_1
|   |  |-- image_1
|   |  `-- image_2
|   |-- split_2
|   |  |-- image_3
|   |  `-- image_4
|   `-- split_etc
|-- 0
|   |-- split_1
|   |  |-- image_1
|   |  `-- image_2
|   |-- split_2
|   |  |-- image_3
|   |  `-- image_4
| …
```

Retrieve files from subdirectories of class directories

---

src/backends/tsne/tsnelib.cc

Now the measure dict only contains the train loss.
```
"measure": {
"train_loss": 0.0
}
```

tsne can now send the number of iterations

---

CMakeLists.txt

Trigger Caffe DEBUG flag during DeepDetect compilation.

Add USE_CAFFE_DEBUG flag

---

src/mlmodel.h
src/simsearch.h

Avoid full index preloading with `index_preload` set to false, forces mmap to not use MAP_POPULATE

added ability to avoid index preloading

---

src/backends/caffe/caffeinputconns.cc
src/backends/caffe/caffeinputconns.h

This PR allows to train images using data from a text file corresponding to the following:
```
path/to/img1 label1
path/to/img2 label2
path/to/img3 label3
```
The main reason of this PR is to facilitate the management of datasets by avoiding having duplicates data when we want to train on several parts of a whole big dataset.
Instead of creating symlinks or copies of images into a folder having the following needed tree;
```
-DATA
- label1
- Image1
- Image2
- etc.
- label2
- Image1
- Image2
- etc.
- etc.
```
One can store images in a fix place and work with txt files containing paths to the images.
The calls to DD remain the same, the only change that need to be made is in the field **data**. Instead of indicating a path of a *root_folder* containing a sub directory per class you'll just …

Train images models from txt files

---

src/backends/caffe/caffelib.cc
src/backends/caffe/caffelib.h
tests/ut-caffe-mlp.cc

example curl at service creation:
```
curl -X PUT "http://10.10.77.61:"$1"/services/seg" -d '{                                                                                                                                                           
"mllib":"caffe",                                                                                                                                                                                                 
"description":"seg dice",                                                                                                                                                                                         …
```

Dice loss parameters + contours : clean API 

---

src/backends/caffe/caffelib.cc
src/csvinputfileconn.cc
src/generators/net_caffe_recurrent.cc
src/generators/net_caffe_recurrent.h

now layers can be
['L50','L50','A3','L3','A3']    meaning two lstm with output size of 50, followed by an affine (inner product) layer for dimension reduction, then another LSTM layer with output size of 3 , and finally another inner product.
N B: this PR is not ready for merge, it is p-requested for jenkins

enlarge recurrent template grammar + cvsts fixes

---

src/backends/ncnn/ncnninputconns.h
src/backends/ncnn/ncnnlib.cc
src/backends/ncnn/ncnnlib.h
src/csvinputfileconn.cc
src/jsonapi.cc
src/services.h

- input + output of timeseries for ncnnlib 
- add templates instanciations for ncnn timeseries
- correclty format input and output for timeseries
- add continuation option for ncnn timeseries, so that it can use saved internal state of lstm
- example for service instanciation : 
```
curl -X PUT "http://10.10.77.61:8080/services/dd_valve" -d '{
{"mllib":"ncnn", "description":"dd valve timeserie simulator",
"parameters":{
"input":{
"connector":"csvts", "db": false,
"label" : ["PRV.port_b.p","PRV.der_alpha.u","PRV.der_alpha.y"],
"ignore": ["time"] },
"mllib":{ "regression":true  }  },
"model":{ "repository":"/home/infantes/ncnn_ts/model/"  }}'
```
- example for prediction: 
```
curl -X POST "http://10.10.77.61:8080/predict" -d '{
{"service":"dd_valve",
"parameters":{ …
```

ncnn timeseries for predictions 

---

src/backends/ncnn/ncnninputconns.h

img ncnn flavor of imgInputConn : mean was applied unconditionally, fixed

apply mean only if it exists in parameters

---

src/supervisedoutputconnector.h

Variable Length Array is a C99 feature and is not supported in C++.
g++ support c++11 AND C99 at the same time but not other compilers.
MSVC is only C90 compliant...

Use a std::vector instead of variable length array

---

src/apistrategy.h
src/ext/rmustache/mustache.cc
src/mlservice.h
src/utils/fileops.hpp
tests/ut-ncnnapi.cc

implement fileops on WIN32 using boost::filesystem
some function are still missing
remove useless includes in ut_nncnnapi.cc
correct some include missing or misconfigured
strcasecmp does not exist on Windows/MSVC so replace it by _stricmp

implement fileops on WIN32 using boost::filesystem, correct includes

---

src/utils/utils.hpp

Use WIN32 API to get processor count on Windows
This is used for ut-ncnnapi test

implement dd_utils::my_hardware_concurrency on WIN32

---

main/dede.cc
src/deepdetect.cc

use USE_HTTP to condionally include httpjsonapi.h
correct not defined to !defined to get correct behavior on Windows

use USE_HTTP to condionally include httpjsonapi.h, correct not defined to !defined

---

src/backends/caffe/caffeinputconns.cc
src/backends/caffe/caffeinputconns.h
src/backends/caffe/caffelib.cc
src/backends/ncnn/ncnninputconns.h
src/csvinputfileconn.cc
src/csvinputfileconn.h
src/csvtsinputfileconn.cc
src/csvtsinputfileconn.h
src/generators/net_caffe.cc
src/generators/net_caffe_recurrent.cc
src/generators/net_caffe_recurrent.h

- do not write default dim values in prototxt (as they are negative, this write overflowed values into prototxt), necessary to debug workflow including editing prototxt by hand (normal / platform workflow is not affected)
- get back old commit from some lost branch that computes min and max from all files including test files, and not only train files + small fix on this part
- do not read bounds for auto unscale at every predict, but only at service init
- scale values between -0.5 and 0.5 instead of 0 and 1, as LSTM sensitive part is around 0
- add residual style LSTM:   in service creation, parameters.mllib.residual = true (false by default) adds every possible short connexion, resnet-style. Unclear if this helps for derivatives, as it was designed for.

timeseries minor fixes

---

CMakeLists.txt
README.md
src/CMakeLists.txt
src/backends/tensorrt/half.hpp
src/backends/tensorrt/protoUtils.cc
src/backends/tensorrt/protoUtils.h
src/backends/tensorrt/tensorrtinputconns.cc
src/backends/tensorrt/tensorrtinputconns.h
src/backends/tensorrt/tensorrtlib.cc
src/backends/tensorrt/tensorrtlib.h
src/backends/tensorrt/tensorrtmodel.cc
src/backends/tensorrt/tensorrtmodel.h
src/ext/rapidjson/document.h
src/ext/rapidjson/reader.h
src/imginputfileconn.h
src/jsonapi.cc
src/services.h

TensorRT backend for prediction. Caffe models are automatically converted and optimized on the first `POST /predict` call. The converted weights are stored on disk, and can be kept  and reused even after the service has been stopped.
- tested on jetson TX2, AGX, nano / jetpack / tensor RT 5.0
- tested for detection (on squeezenet-ssd) and image classification (on vgg16, googlenet and resnet_18)
- API for service creation:
```
curl -X PUT http://localhost:8080/services/squeezenet_ssd_voc -d '{
"description": "Squeezenet SSD",
"model": {
"repository": "/path/to/model_ssd"
},
"mllib": "tensorrt",
"type": "supervised",
"input": {
"width":300,
"height":300
},
"mllib" : {
"datatype": "fp32",
"maxBatchSize": 4,
"maxWorkspaceSize": 1024
}
}
}'
```
- API for …

Tensor RT 5.0 backend

---

src/backends/caffe/caffelib.cc

Instead of removing bad bbox, this PR regularizes the size of the bbox to the boundaries of the image.
This can be usefull when an object is not completly present in the image (the bounding box might exceed the size of the image)

Regularize bad bbox to the boundaries of the image

---

src/backends/ncnn/ncnnlib.cc

this patch checks NCNN model reads status and throw exceptions in case of errors, fixes #610

FIX: do not segfault when cannot find ncnn model files

---

src/utils/fileops.hpp
tests/ut-caffeapi.cc

boost::filessytem based listing/removal of files
TESTED OK on vanilla ubuntu and xfs

patch to make deepdetect xfs compliant

---

CMakeLists.txt
src/CMakeLists.txt
src/backends/ncnn/caffe2ncnn.cc
src/backends/ncnn/caffe2ncnn.h
src/backends/ncnn/ncnnmodel.cc

This patch allows deepdetect to generate automatically ncnn model files from caffe ones if possible and if needed. no API change

autogenerate ncnn model files from caffe ones if possible and if needed

---

src/backends/ncnn/ncnnlib.cc
src/backends/ncnn/ncnnlib.h

when omitted, previous hardcoded default are used
example usage:
```
curl -X PUT "http://10.10.77.61:"$1"/services/lieb_test" -d '{
"mllib":"ncnn",
"description":"input output blob test",
"parameters":{
"input":{
"connector":"csvts",
"db": false,
"label" : ["out1","out2","out3"],
"ignore": ["time"]
},
"mllib":{
"inputblob":"data",
"outputblob":"rnn_pred",
"gpuid" : 1,
"db": false
}
},
"model":{
"repository":"/path/to/repo"
}
}'
```

NCNN backend : add inputblob and ouputblob option to mllib at service creation time

---

src/jsonapi.cc
src/jsonapi.h

Changed behavior when running from command line so that an error will cause dede to exit by default (configurable with a command line parameter to disable this behavior). When using jsonapi otherwise, the default behavior is still to not exit on failure.
If different exit values are preferred for different cases, I can make that change.

Exit on failure from command line start list behavior

---

src/backends/caffe/caffelib.cc

it seems that at some point, solver type selection API has changed in caffe, and we are still using the old version which is not honored anymore by caffe (when overriding solver type directly in memory)

CRITICAL FIX: caffe solver selection

---

src/backends/caffe/caffelib.cc

dede API for lookahead solver, see https://github.com/jolibrain/caffe/pull/49
train options (with default values): 
parameters.solver.lookahead : false,
parameters.solver.lookahead_steps : 6,     
parameters.solver.lookahead_alpha : 0.5
set first option to true for using 
TESTED OK (over ADAM)

dede API for lookahead

---

src/backends/caffe/caffelib.cc

add API for caffe warmup (see https://github.com/jolibrain/caffe/pull/50)
parameters.mllib.solver.warmup_lr : initial lr (lr is computed linearly from warmup_lr to base_lr between 0 and warmup_iter)
parmeters.mllib.solver.warmup_iter : number of warmup iterations
TESTED OK (against correct caffe)

dd api for caffe warmup

---

src/backends/caffe/caffelib.cc

sane defaults based on max_iter
original sheduler for decoupled weight decay uses restarts and a cosine variation between two restarts
new parameters are:
number of search periods to do before max_iter: parameters.solver.decoupled_wd_periods  [default : 4]
multiplier of period  at every restart : parameters.solver.decoupled_wd_mult [default: 2]

add API params for decoupled weight decay scheduler

---

CMakeLists.txt
README.md
patches/pytorch/pytorch_log.patch
src/CMakeLists.txt
src/backends/torch/torchinputconns.h
src/backends/torch/torchlib.cc
src/backends/torch/torchlib.h
src/backends/torch/torchmodel.cc
src/backends/torch/torchmodel.h
src/imginputfileconn.h
src/jsonapi.cc
src/services.h
tests/CMakeLists.txt
tests/ut-torchapi.cc
tools/torch/README.md
tools/torch/trace_torchvision.py

- Libtorch backend
- Libtorch image input connector
- Image classification using pytorch traced models
- Downloading and compiling libtorch automatically during DeepDetect compilation
- Unit tests on libtorch backend
Building instructions:
```
cmake .. -DUSE_TORCH=ON
```

Integration of Libtorch in DeepDetect for image classification

---

CMakeLists.txt

```
cmake -DUSE_CUDNN=ON -DUSE_SIMSEARCH=ON -DUSE_TSNE=ON -DUSE_XGBOOST=ON -DUSE_TORCH=ON -DUSE_NCNN=ON -DUSE_TENSORRT=ON -DCUDA_ARCH="-gencode arch=compute_61,code=sm_61" ..
make
```
now builds the project successfully

Fix Protobuf conflict preventing complete build

---

src/services.h

A set of fixes and improvement to the `/chain` API:
- Avoid logger lock by catching all errors at higher level
- Stopping and returning existing results from chain in case of error or lack of data to pursue
- Fix to meta URIs trickling down the tree

Fixes to chain, improving error handling

---

CMakeLists.txt
src/CMakeLists.txt
src/backends/ncnn/caffe2ncnn.cc
src/backends/ncnn/ncnnlib.cc
src/backends/ncnn/upgrade_proto.cpp
src/backends/ncnn/upgrade_proto.hpp

fix caffe2ncnn conversion for deprecated weights format (googlenet, vgg16)
- some of our pretrained weights are in V0 or V1 format, and V2 is required
- old caffe2ncnn did not do V[0|1] -> v2 conversion, which prevented googlenet and vgg16 pretrained to be used with ncnn
- this commit uses caffe code to do conversion where needed 
TESTED OK

fix caffe2ncnn conversion for deprecated weights format 

---

src/imginputfileconn.h

This PR allows to control OpenCV interpolation method via the API:
```json
{
"parameter": {
"input": {"connector":"image", "interp": "linear"}
}
}
```
The `interp` API parameter takes values from `"linear","nearest","cubic","area","lanczos4"`. 
Fastest methods are `"nearest"` then `"linear"`, default remains `"cubic"`.

input image interpolation method selection via API

---

CMakeLists.txt
clients/python/dd_bench.py
src/backends/caffe/caffeinputconns.h
src/chain_actions.cc
src/imginputfileconn.h

This PR adds OpenCV GPU support (NVidia only) for image input resizing operation. This functionality **requires an OpenCV builds with CUDA support**.
API changes
- `input.cuda` boolean to resize input images on GPU
Build flag
- `-DUSE_CUDA_CV=ON` passed to `cmake`
Results:
- Early tests on Jetson TX2 shows up to 20% speed gain on single image with large size (e.g. 4000x4000)
- Speedup may vary depending on GPU

OpenCV GPU support with CUDA for image input resizing

---

src/backends/caffe/caffelib.cc

This PR adds controls over the following SSD parameters at service/model creation time (from template), the `mllib` object:
- `ssd_expand_prob`: probability of expanding the image (to improve detection of small/very small objects)
- `ssd_max_expand_ratio`: bbox zoom out ratio
- `ssd_mining_type`: `"HARD_EXAMPLE"` or `"MAX_NEGATIVE"`
- `ssd_neg_pos_ratio`: ratio of negative sampled examples wrt positive examples (bbox)
- `ssd_neg_overlap`: max overlap of negative samples with positive samples (bbox)
- `ssd_keep_top_k`: keep k examples after nms has finished
The default values remain that of every SSD template, and are only overridden when specified through API.

Additional API control over useful SSD training / deploy parameters

---

src/backends/caffe/caffeinputconns.cc
src/csvinputfileconn.h
src/csvtsinputfileconn.cc
src/csvtsinputfileconn.h
src/imginputfileconn.h
src/inputconnectorstrategy.h
src/svminputfileconn.h
src/txtinputfileconn.h
src/utils/httpclient.hpp

This PR adds timeout control to the input connector, via `parameters.input.timeout`:
- at service creation, and stays the default value through the service's life
- can be overridden with every `/predict` call
Additional elements:
- default timeout is set to 600 seconds (10 mins)
- there's a max timeout value set to 36000 seconds (10 hours), any timeout set above that threshold leads to a 400 error.

Added input connector timeout, ref #647

---

src/supervisedoutputconnector.h

This PR add a measure named 'raw' that outputs raw results as a measure, ie that outputs ground truths, prediction and associated confidence for classification tasks
example:
curl -X POST 'http://localhost:8080/predict' -d '{
"service":"classif_service",
"parameters":{
"mllib":{
"gpu":true
},
"output":{
"measure":["raw"]
},
"data":["test_data"]
}'
example output:
{'status': {'code': 200, 'msg': 'OK'}, 'head': {'method': '/predict', 'service': 'classif_service'}, 'body': {'time': 349.0, 'measure': {'learning_rate': inf, 'raw': {'confidences': [0.9979221224784851, 0.9974542260169983, 0.9999772310256958, ...], 'estimations': ['P3', 'P3', 'P2',...],'truths': ['P3', 'P3', 'P3',...] }}}}

'raw' measure for classification tasks

---

src/supervisedoutputconnector.h

WIP : 
we need to decide how to pass the data wrt prediction/test   memorydatalayer/AnnotatedDataLayer

Raw detection output if measure = raw

---

src/backends/torch/torchinputconns.h
src/backends/torch/torchlib.cc
src/imginputfileconn.h
tests/ut-torchapi.cc

Small fixes and improvements to torch model inference:
- return all classes with `"best":-1`
- cleaner error message when model location is wrong
- allowing `std` as a vector of `float`
- introducing `scale` as an option to scale the image values
The torch image classification model service creation and prediction become:
- service creation
```json
curl -X PUT "http://localhost:8080/services/torch_resnet" -d '{
"description": "image classification service",
"model": {
"repository": "/path/to/resnet50_torch/"
},                   
"input": {                                                            
"connector": "image"
},"mllib":{}
},              
"type": "supervised"
}     
'
```
- prediction 
```json
curl -X POST "http://localhost:8080/predict" -d '{ …
```

Pytorch inference fixes

---

src/backends/tensorrt/tensorrtlib.cc
src/backends/tensorrt/tensorrtlib.h

This protects against parallel calls that may fill the GPU memory up. Batches should be used instead.

Add mutex to TensorRT prediction calls

---

src/chain_actions.cc
src/imginputfileconn.h
src/services.h

This PR should speed up chains with many crops, removing the encoding and serializing steps.

Chains: avoid encoding + serializing crops, passing raw cv::Mat instead

---

templates/caffe/crnn_se_resnet_50/crnn_se_resnet_50.prototxt
templates/caffe/crnn_se_resnet_50/crnn_se_resnet_50_solver.prototxt
templates/caffe/crnn_se_resnet_50/deploy.prototxt
templates/caffe/crnn_se_resnext_50/crnn_se_resnext_50.prototxt
templates/caffe/crnn_se_resnext_50/crnn_se_resnext_50_solver.prototxt
templates/caffe/crnn_se_resnext_50/deploy.prototxt

This allows finetuning strong OCR models from pre-trained squeeze-excitation ResNet architectures.

added caffe templates for OCR crnn with SE-ResNet-50 and SE-ResNext-50

---

docker/cpu-caffe-tf/Dockerfile
docker/cpu-ncnn-pi3/Dockerfile
docker/cpu/Dockerfile
docker/gpu-caffe-cpu-tf/Dockerfile
docker/gpu-caffe-tf/Dockerfile
docker/gpu-caffe2/Dockerfile
docker/gpu-p100/Dockerfile
docker/gpu-volta/Dockerfile
docker/gpu/Dockerfile

- Bazel version 0.24 for TF builds
- Maintainer name update
- All builds based on CUDA 9 to avoid unsupported ops in CUDA 8.

Update to docker files

---

src/chain_actions.cc
src/chain_actions.h

Image rotation action, typically useful prior to an OCR model that requires an element with text is correctly rotated. 
The `rotate` action is to be used as follows:
- within a chain:
```
{                                                                                                     
"action": {                                                                                          
"type": "rotate"                                                                                 
}                                                                                                    
}
```
- action takes the output label of a classifier model that **must** be one of the following strings: `["0","90","180","270"]` as the rotation angle in degrees. The output of the action is then the …

Image rotation action, usable in `chains`

---

src/backends/caffe/caffelib.cc

TESTED OK : consistently better with several solvers, at no cost
API for lr dropout as implemented in caffe in https://github.com/jolibrain/caffe/pull/58
https://arxiv.org/abs/1912.00144
default : disabled
beware : this is not a dropout value (ie a probability of setting zero), but the opposite (as in the paper: the probability of not changing the value, default to 1, meaning no dropout)

learning rate dropout API, see 1912.00144

---

src/backends/caffe/caffelib.cc
src/backends/ncnn/ncnnlib.cc
src/backends/tensorrt/tensorrtlib.cc
src/chain_actions.cc

FIX https://github.com/jolibrain/deepdetect/issues/674
- ymin and ymax were previoulsy swapped, ie ymin was > ymax 
- this patch correctly set ymin and ymax so that it respects caffe detection_ouput layer semantics as for instance in https://github.com/jolibrain/caffe/blob/master/src/caffe/layers/detection_output_layer.cpp#L368
- when using output of detection models, if ymin and ymax are used as is, then problems are to be exepcted, but if they are used with somthing like height = abs(ymin-ymax) , then this patch will not change anything.

Fixed inversion of ymin and ymax in detection models output

---

CMakeLists.txt
README.md

this PR 
- cleans up cmake build file in order to build cleanly against TensorRT 5, 6 and 7 
- allows to build agains oss parts of tensorRT + closed tensorRT 
compile dede with : 
- `-DUSE_TENSORRT=ON` for full closed source version and 
- `-DUSE_TENSORRT=ON -DUSE_TENSORRT_OSS=ON` for tensorrt + open source parts

tensort RT 7 + OSS

---

src/backends/caffe/caffelib.cc
src/supervisedoutputconnector.h

this PR allows to ouput  logits in raw measure
needs caffe as per https://github.com/jolibrain/caffe/pull/61
for detection, needs deploy.prototxt to be a test net + updates as detailed in https://github.com/jolibrain/caffe/pull/61
API for detection:
parameters_output = {'confidence_threshold':0.01,  'measure':['raw'], 'logits':True}    
API for classification:
parameters_output = {'measure':['raw'], 'logits_blob': "logits_blob_name"}

Detection calibration

---

.travis.yml

Travis builds appear to fail on github with error `/home/travis/.travis/functions: line 109: ./configure: No such file or directory`

Tentative fix to travis file

---

src/supervisedoutputconnector.h

in case of very small randomly selected test sets, f1 and conf matrix may have been divided by zero before this fix. happened in torch unit tests

do not divide by zero f1 and conf_matrix if nothing in category

---

src/backends/caffe/caffelib.cc
src/backends/caffe/caffelib.h

This PR adds passing geometric image deformation option to AnnotatedDataLayer when instanciating template. 
since https://github.com/jolibrain/caffe/pull/67 , annotatedDataLayer can deform image using zoom in/out, perspective change (right/left/top/bottom) and consistently deforms bboxes
TESTED OK

geometry image deformation for detection/ssd

---

src/backends/dlib/dlib_actions.cpp
src/backends/dlib/dlib_actions.h

(merged) PR 693 [add logger to chain] breaks dlib backend (ie dlib chain actions were coded for version w/o logger). This PR fixes that

fix wrt PR 693 (dlib chain / logger)

---

src/backends/caffe/caffelib.cc
src/backends/caffe/caffelib.h

this PR allows to select engine (cudnn or caffe (which is CPU or GPU depending on GPU availability)) at service creation time, for layers that can, ie conv, deconv, tanh, relu, sigmoid, pooling, lrn, and softmax.
This is a workaround to memory over consumption / leakage seen with some models that do a _lot_ of cudnncreate 
if unset, use default, which is cudnn is deepdetect+caffe was compiled with -DUSE_CUDNN=ON , or caffe in other case
parameter is parameters.mllib.engine  , can be set to "CUDNN" or "CAFFE"
example: 
curl -X PUT http://localhost:8080/services/ocr -d '{
"description": "ocr",
"model": {
"repository": "/home/infantes/airbusey_comp_ocr_resnext50_v4"
},
"mllib": "caffe",
"type": "supervised",
"input": {
"width":250,
"height":200, …

engine selection at service creation time : CAFFE of CUDNN

---

src/backends/caffe/caffelib.cc
src/backends/caffe/caffelib.h

(de)conv with dilation > 1 in conjunction with cudnn engine option are rejected by caffe. this PR forces CAFFE engine for such cases even if cudnn is specifically asked for 
mllib.engine options are now:
"DEFAULT" : caffe default : ie CPU/CUDA/CUDNN depending on caffe compilation (and internally forces  CUDA/CPU if dilation > 1)
"CAFFE": force caffe engine, ie no cudnn (CPU or CUDA depending on caffe compilation)
"CUDNN": vanilla caffe cudnn implementation,(ie multiple_handle)
"CUDNN_SINGLE_HANDLE" : uses less memory than CUDNN
"CUDNN_MIN_MEMORY" : forces minimum memory algorithms
if dilation > 1, DEFAULT is forced on

fix: force  caffe engine  when (de)conv dilation > 1

---

src/chain_actions.cc

Bug was affecting rotate action + OCR.

Fix rotate action when upstream prediction is empty for some of the samples in a batch

---

CMakeLists.txt

add explicit -lprotobuf in case of no caffe
(in case of caffe, caffe added it)

fix compile w/ trt w/torch w/o caffe

---

src/backends/caffe/caffelib.cc

This fixes a bug affecting model publication on DD platform with the new `engine` selection scheme #696

fixed model copy calls between directories (aka publishing) with deploy modified

---

.dockerignore
docker/README.md
docker/cpu-arm.Dockerfile
docker/cpu.Dockerfile
docker/gpu-xenial.Dockerfile

This PR update Docker base image from Ubuntu 16.04 LTS to  **Ubuntu 18.04 LTS**.
**Notes :**
* ARM : Base image [armhf/ubuntu](https://hub.docker.com/r/armhf/ubuntu) is deprected. We switch on [arm32v7/ubuntu](https://hub.docker.com/r/arm32v7/ubuntu/).
* CUDA : Cuda 9.0 is not available with Ubuntu 18.04 base image. We update CUDA from version 9.0 to **10.2** per default. 
* Caffe2 cannot build with Ubuntu 18.04 Docker base image. Dockerfile `gpu-xenial.Dockerfile` is a fallback solution.

Update all Docker images to Ubuntu 18.04

---

templates/caffe/resnet_18_ssd/deploy.prototxt
templates/caffe/resnet_18_ssd/resnet_18_ssd.prototxt
templates/caffe/resnet_18_ssd/resnet_18_ssd_solver.prototxt
templates/caffe/resnet_34_ssd/deploy.prototxt
templates/caffe/resnet_34_ssd/resnet_34_ssd.prototxt
templates/caffe/resnet_34_ssd/resnet_34_ssd_solver.prototxt

Goal is to have object detection architecture to fill the gap between light and heavy designs without sacrificing much accuracy.
- Root-ResNet-34-SSD modified from ScratchDet https://github.com/KimSoybean/ScratchDet
- Root-ResNet-18-SSD
At least one more model to come. These will be translated to torch when migration is in place.

Additionnal ResNet-SSD intermediate architecture templates

---

src/backends/caffe/caffelib.cc

this PR fixes predict call for regression based on images. This was a wrong slot number in output matrix

[FIX] image based  regression predict

---

src/backends/caffe/caffelib.cc
tests/ut-caffe-mlp.cc

- caffe dice connexion with prototxt was still done as in an old version of dice layer, fix is to use general case (ie >2 classes)
- dice contour weighting has a bug (normalization ??) disabling it for now

[FIX] dice loss for 2 classes + contour weighting

---

src/supervisedoutputconnector.h

this PR adds support for the case where 
- `raw` measure is asked for (for external model eval)
- logits are not in the output (ie model eval w/o calibration : case of torch models as of 2020 05 20 )

[FIX] case where nologits available but raw measure asked for

---

src/backends/caffe/caffeinputconns.cc
src/backends/caffe/caffeinputconns.h

this PR fixes this segfault :
do not honor db flag in case of predict for svm caffe input connector

[FIX] segfault in case of predict with svmCaffeInputConn and db:true

---

src/backends/caffe/caffelib.cc
src/supervisedoutputconnector.h

fix reversed precision and recall in test outputs
also output every precision, recall and f1 if `measure=[..., "f1full"]`
global f1 computation has slightly changed : 
it is now the mean of per class f1, while before it was f1 score computed on mean recalls and precisions
(ie the mean and f1  operators have switched)

[FIX] reversed precision and recall in case of classification + output all (per class) precision,recall,f1 if asked for

---

src/backends/caffe/caffeinputconns.cc

Added key overflow warning at end of db serialization when an image key > 256 chars

---

CMakeLists.txt

Currently dmlc/rabi have been removed from master branch of xgboost
`git clone --recursive` will clone submodule of master branch, so `rabi`
is missing. Then we switch to an old xgboost version and it can't build
because of the missing deps.
This change retrieves submodule after we switch to the wanted commit-id.

fix(build): ensure all xgboost submodules are checkouted

---

Jenkinsfile

This uses `post` instead `stage` to always report the status to
rocketchat.
The avatar have been removed as it doesn't work anymore.

ci: fix rocketchat reporting

---

Jenkinsfile
ci/Jenkinsfile.pytorch-cache

This will catch all kind of Jenkins error.

fix(ci): use unsuccessful instead of failure

---

src/backends/caffe/caffelib.cc
src/backends/caffe/caffelib.h

Size and color channels are now configurable in segmentation tasks with Caffe.

fix: allows to specify size and color/bw with segmentation models

---

src/mllibstrategy.h
src/mlservice.h

It doesn't make sense to have separate methods
collect_measures() and est_remain_time(). And we need to call them in a
row to generate `remain_time_str` key.
The tflops measure was available for a service, but not during the
training.
This change adds it to the training status.
Fixes #785

feat(trains-status): add tflops to body.measures

---

src/backends/caffe/caffelib.cc

Huber loss has threshold set to 1.
One issue to be careful about is whether we do use normalized targets in time-series regression typically. And in that case, this PR should be updated with a configurable `sigma_l1` parameter for the smooth l1 loss.
References : 
- https://stats.stackexchange.com/questions/351874/how-to-interpret-smooth-l1-loss
- https://pytorch.org/docs/stable/generated/torch.nn.SmoothL1Loss.html#torch.nn.SmoothL1Loss

fix: set caffe smooth l1 loss threshold to 1

---

CMakeLists.txt
patches/trt/0001-support-for-refinedet.patch

this PR fixes refinedet over TensorRT
- inputs blob id were swapped 
- detection output layer / refinedet case was not correctly saved upon serialization / deserialization
- deserialization from existing engine did not work  : bug in upstream tensorrt-oss (namely (de)serialization of normalize layer and (de)serialization of priorboxlayer), fixed upstream since juillet 2nd,  make dede depend on this fixed version

fix(TRT): refinedet

---

CMakeLists.txt
ci/Jenkinsfile.unittests

Sets Jenkins to build with TENSORRT_OSS as default since it's now the
most recent and advanced.

fix: build with -DUSE_TENSORRT_OSS=ON

---

src/backends/caffe/caffemodel.cc
src/utils/fileops.hpp

simple change to replace db:true by db:false in json files when copying models , as reported by laura a few weeks ago

replace db:true by db:false in json files when copying models

---

src/backends/caffe/caffeinputconns.cc
src/backends/caffe/caffeinputconns.h
src/svminputfileconn.cc
tests/ut-caffeapi.cc

This PR also adds:
- `test_split` support for training neural nets from SVM data format with db
- SVM data training with db is added to unit tests

Fixed svm with db training

---

CMakeLists.txt
src/backends/ncnn/caffe2ncnn.cc
src/backends/ncnn/upgrade_proto.cpp
src/backends/ncnn/upgrade_proto.hpp
src/backends/tensorrt/protoUtils.cc
src/backends/tensorrt/tensorrtlib.cc
src/backends/torch/native/templates/nbeats.h
src/backends/torch/torchinputconns.cc
src/backends/torch/torchlib.h
src/backends/xgb/xgb_dmlc_macro_fix.h
src/backends/xgb/xgbinputconns.h
src/backends/xgb/xgblib.h
src/caffegraphinput.h
src/generators/net_caffe.h

Depending on the version of protoc the warning differ.
So we need to filter all of them.
second parameter is ignored and deprecated.

Pull request for Werror

---

src/backends/caffe/caffeinputconns.cc
src/backends/caffe/caffeinputconns.h
src/csvinputfileconn.cc
src/csvinputfileconn.h
src/csvtsinputfileconn.cc
src/csvtsinputfileconn.h

This PR should fix #837. 
It adds support for categorical variables when training from time-series (in multiple CSV files format). This works both with and without using the underlying `db` with caffe typically.
~~TODO: this is untested with torch backend for timeseries at the moment.~~
Works fine with torch backend.

fix: add support and automated processing of categorical variables in timeseries data

---

docs/api.md

Alias rule allows the redirection of https://www.deepdetect.com/api to https://www.deepdetect.com/server/docs/api/

fix: /api/ alias when deployed on deepdetect.com

---

src/backends/torch/native/templates/nbeats.cc
src/backends/torch/native/templates/nbeats.h

previous version of extention of nbeats multi-dimensional case used a too early decompression of internal representation, leading to prohibitive memory usage (ie 1000 timesteps * signal of dimensionality 1000 did not fit into memory). With this PR, we now decompress internal representation as far as possible, leading to a much more sensible memory consumption

Nbeats : lower dim of internal fully connected layer

---

src/services.h

This aims to make the code flow looks like we don't have visitor in the
loop.
The idea is to put all visitor of a particular base class, into
dedicated namespace. Each visitor will have a static method in this
namespace where we move all of visitor boilerplate setup. This avoid
creating intermediate object to store the method result. Using a visitor
become a simple as:
`int status = visitor_mllib::predict_job(mllib, ad_in, ad_out, chain);`
The visitor helper signature looks like the real mllib method.
This applies the same logic for other service visitors.

refactor: hide visitor complexity inside the visitor itself

---

src/backends/caffe/caffelib.cc

Allows modifying the underlying cudnn execution strategy from the DD API on trained models, for inference.

fix: update caffe cudnn engine without template

---

src/backends/caffe/caffelib.cc
src/backends/torch/torchgraphbackend.cc
src/backends/torch/torchlib.cc
src/basegraph.cc
src/caffegraphinput.cc
src/generators/net_caffe_recurrent.cc
src/generators/net_caffe_recurrent.h
tests/ut-graph.cc

this PR adds support for lstm autoencoders using graph/torch API
API follows classical LSTM call:
service creation 
```
curl -X PUT "http://localhost:8800/services/autoencoder" -d '{
"mllib":"torch",
"description":"lstm_autoencoder",
"model": {
"repository":"/path/to/repo"
},
"parameters" : {
"input": { 
"connector":"csvts",
"label":["output"] 
},
"mllib" : {
"template" : "recurrent",
"layers":["L10","L10","T","L10"],
"loss":"L1"
}
}
}'
```
`T` means Tile, original caffe layer name that repeats one blob along a dimension. Here last hidden value of the encoder is  repeated / tiled to serve as input for all decoder inputs. 
exemple training:
```
curl -X POST "http://localhost:8800/train" -d '{
"service":"autoencoder", 
"async":true,
"parameters" : {
"input" : { …
```

Graph lstm autoencoder

---

tests/ut-torchapi.cc

The test fails sometimes because the accuracy is not good enough.
This increases the number of iteration to be sure the accuracy will good
enough.

fix(tests): inc iteration of torchapi.service_train_image test

---

src/backends/torch/torchinputconns.cc

previous behavior was to silently discard

csvts / torch :  warn if there is not enough timesteps in a sequence

---

build.sh

They is no need to build all arch for some dev/testing.
Since this have a huge impact on the compilation time,
this allow to configure the list.
This also adds cards supported since cuda 10

feat(build): allow to change CUDA_ARCH

---

docs/api.md
src/backends/torch/native/templates/nbeats.h

now template_params can be of the form ["t3","s10","g20","b10",'h25"]  where h denotes a hidden size of 25

Feat nbeats expose hidden size in api

---

src/backends/ncnn/caffe2ncnn.cc

comment: default limit is already set to INT_MAX
CPU builds with caffe + ncnn were failing:
```
/opt/deepdetect/src/backends/ncnn/caffe2ncnn.cc: In function 'bool read_proto_from_binary(const char*, caffe::NetParameter*)':
/opt/deepdetect/src/backends/ncnn/caffe2ncnn.cc:340:38: error: no matching function for call to 'google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int)'
codedstr.SetTotalBytesLimit(INT_MAX);
^
In file included from /opt/deepdetect/src/backends/ncnn/caffe2ncnn.cc:28:0:
/usr/include/google/protobuf/io/coded_stream.h:386:8: note: candidate: void google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int, int)
void SetTotalBytesLimit(int total_bytes_limit, int warning_threshold);
^~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/io/coded_stream.h:386:8: note: …
```

fix: remove unecessary limit setting call to protobuf codedstream

---

src/backends/torch/native/native_net.h
src/backends/torch/native/templates/nbeats.cc
src/backends/torch/native/templates/nbeats.h

this PR makes nbeats use torch registration of constant matrices, makes all explicit calls to "to" superfluous

refactor: register internal matrices in nbeats, makes code a lot simpler

---

src/backends/torch/torchinputconns.cc
src/csvtsinputfileconn.cc
src/csvtsinputfileconn.h

this PR is a small fix on stored file names ins csvts input file names, it is necessary per new warning that raises if some file is too short to build even one timeserie

fix(csvts): correctly store and print test file names

---

src/backends/torch/torchlib.cc
src/backends/torch/torchlib.h

this PR unscale the output at prediction time, exaclty as in caffe backend. This step was previously wrongly skipped

fix(torch/timeseries): unscale prediction output if needed

---

docs/api.md
src/supervisedoutputconnector.h
tests/ut-graph.cc

this PR adds timeseries specific metrics , ie MAPE (output.metrics.mape) sMAPE (as output.metrics.smape) MASE (as output.metrics.mase) and OWA (as output.metrics.owa); see https://arxiv.org/abs/1905.10437 for equations

feat(timeseries): MAPE, sMAPE, MASE, OWA metrics

---

src/backends/torch/torchlib.cc
src/imginputfileconn.h
tests/ut-torchapi.cc

Classification head was added if there was a traced model, which was not the expected behavior in some cases. It was also added on prediction models in some cases, making them totally useless.
Now the classification layer is added only if we are training with `finetuning:true`.
EDIT: Not sure why it makes nbeats tests fail, I will check that out
EDIT: Seems like the nbeats issue happens randomly, I saved the backtrace for further investigation. This is not related to this PR.

fix(torch): Fix conditions to add classification head.

---

src/backends/torch/torchinputconns.cc

get_data() is done at the very beginning of CSVTS::transform, these are remains of some very old refactor around the init() just above

fix(torch/timeseries): do not double read query data

---

docs/api.md

Fix issue #869
I did not remove `scale_min` & `scale_max` because they may be used for some models (detectron ? see commit https://github.com/jolibrain/deepdetect/commit/8d3a16525ce1ee56f204b6d27c3b898aa96d5e5a)

docs: Fix documentation for scale in ImageInputConntector

---

src/backends/tensorrt/tensorrtlib.cc
tests/ut-tensorrtapi.cc

- protocol buffer library isn't shutdown when delete a service
- compiled models are correctly removed with clear=mllib API call
Discovered the protobuf issue after modifying the unit tests to destroy the services and cleanup the TRT models: the second TRT service would crash on parsing the model.

fix: proper cleanup of tensorrt models and services

---

src/backends/torch/torchinputconns.cc

uri was wrongly read , leading to segfault

fix(csvts/torch): allow to read csv timeserie directly from query

---

README.md

nobody is connected on IRC channel, so we shouldn't promote it.

docs: remove IRC link

---

src/backends/torch/torchgraphbackend.cc
src/backends/torch/torchgraphbackend.h
src/backends/torch/torchlib.cc
src/backends/torch/torchlib.h
src/caffegraphinput.cc
src/caffegraphinput.h

this PR tries to cleanup model loading in torchlib.cc, previous version was extra cautious , leading to many unnecessary loadings which caused major slowdowns at inference

fix(torch): load weights only once

---

src/apidata.cc

This was causing the error `Error code 1007: conversion error: unknown type` on resuming model training, due to the `flops` value in `metrics.json` being `long int` aka `int64` for `rapidjson`.

fix: handle int64 in conversion from json to APIData

---

src/backends/tensorrt/tensorrtinputconns.cc
src/backends/tensorrt/tensorrtlib.cc
src/backends/tensorrt/tensorrtlib.h
src/backends/tensorrt/tensorrtmodel.cc
src/backends/tensorrt/tensorrtmodel.h
tests/CMakeLists.txt
tests/ut-tensorrtapi.cc

TensorRT backend can now parse and convert ONNX model to TRT engines, and execute them as well.
The model in the repository must be named `net_tensorRT.onnx` otherwise it will not be detected.

feat(tensorrt): Add support for onnx image classification models

---

docs/api.md
src/backends/tensorrt/tensorrtlib.cc
src/backends/tensorrt/tensorrtlib.h

This PR adds support for compiling models that end with a regression head. It hasn't been added to the unit tests since we don't have image regression models in our examples set yet.

feat(ml): tensorrt support for regression models

---

src/backends/torch/torchlib.cc

naive instantiation is deferred to predict/training time, one should not try to load weight during init_mllib (this happens when predicting only, ie w/o training first)

fix(torch/native): prevent loading weights before instanciating native

---

docs/api.md
src/backends/caffe/caffelib.cc

this PR exposes news caffe optimizer flavors to dede API
solver_param.adabelief bool       https://arxiv.org/abs/2010.07468
solver_param.gradient_centralization bool   https://arxiv.org/abs/2004.01461v2
these are enabled only if ADAM is selected (they are not implemented other cases)
it also adds shortcuts: 
solver_param.solver_type = "RANGER"
selects : 
solver_type = ADAM
solver_param.rectified   true
solver_param.lookahead : true
and
solver_param.solver_type = "JOLIBRAIN_DEFAULT"
selects:
solver_type = ADAM
solver_param.rectified   true
solver_param.lookahead : true
solver_param.adabelief : true
solver_param.gradient_centralization : true
(ie RANGER + ADABELIEF + gradient centralization, it is not clear if gradient centralization is part of ranger or not)

feat(caffe): add new optimizers flavors to API

---

src/generators/net_caffe_recurrent.cc

this PR fixes dropout reading for generating prototxt 
this should fix ut_graph.graphapi.lstm_autoencoder spurious failure

fix(graph): correctly discard dropout

---

CMakeLists.txt
docs/source.md

0.13 don't work correctly with deepdetect.
The build was working on CI because deepdetect was built with the wrong
header and the ABI is compatible.
This downgrade it to 0.11.2 and fix the headers inclusion.

ci: downgrade cppnet to 0.11.2

---

src/apidata.h

This PR fixes execution of `chains` that are only partially executed. This is because the inner APIData structure is not cleaned up and remains in a partial state that was throwing on JSON conversion.
This is not optimal but fixes chains and falls back to previous behavior (ignoring unsupported types upon JSON conversion)

fix: ignore JSON conversion throw in partial chains output

---

src/backends/torch/torchlib.cc
src/backends/torch/torchmodule.cc
src/backends/torch/torchsolver.cc
src/backends/torch/torchsolver.h

this PR forces to reload solver state on device ask for by API. It was loaded on device were it was computed leading to error if this device did not exist (learning on gpuid3 then trying to resume on host with only 3 gpus). It was certainly messing around also if resuming on another device

fix(torch): reload solver params on device from current learning, not previous one

---

tests/ut-torchapi.cc

sometimes jenkins failed because predicted value is -1.015 while test tries to ensure it is >= -1

chore(torch): give more tolerance to unit test

---

CMakeLists.txt

cmake 3.10 is default on Ubuntu 18.04.

fix(build): allow cmake 3.10 (Ubuntu 18.04) for builds with -DUSE_CPU_ONLY=ON

---

ci/Jenkinsfile.unittests
docs/api.md
src/backends/torch/native/native_net.h
src/backends/torch/native/templates/nbeats.cc
src/backends/torch/native/templates/nbeats.h
src/backends/torch/torchlib.cc
src/backends/torch/torchlib.h
src/backends/torch/torchmodule.cc
src/backends/torch/torchmodule.h
src/backends/torch/torchutils.cc
src/backends/torch/torchutils.h
tests/CMakeLists.txt
tests/ut-torchapi.cc

This PR adds multi-GPU support to model training with libtorch, and uses NBeats implementation as a testbed + unit tests.

feat(torch): Add multigpu support for native models training

---

README.md
docs/api.md
src/backends/torch/torchinputconns.cc
src/backends/torch/torchinputconns.h
src/backends/torch/torchlib.cc
src/backends/torch/torchlib.h
src/backends/torch/torchmodule.cc
src/backends/torch/torchmodule.h
tests/ut-torchapi.cc

This PR adds support regression on image models with the `torch` model.
This includes the reading of datasets in the standard DD form of a list of image path and regression targets.
On the side it slightly refactors the dynamic adding of a linear layer on top of of a pretrained torch model, since this is applicable to both `classification` and `regression` cases.

feat(ml): image regression model training with libtorch

---

ci/Jenkinsfile.docker
ci/Jenkinsfile.unittests

We should always run the job to check at least it build.
It doesn't take too much times.

ci: skip only tests with ci:skip

---

tests/ut-torchapi.cc

This fixes the broken cleanup of directories in torch unit tests.

chore: make sure model files don't remain in torch training unit tests

---

src/CMakeLists.txt
src/backends/torch/native/native_factory.cc
src/backends/torch/native/native_factory.h
src/backends/torch/native/templates/vit.cc
src/backends/torch/native/templates/vit.h
src/backends/torch/torchlib.cc
src/backends/torch/torchmodule.cc
src/backends/torch/torchmodule.h
tests/ut-torchapi.cc

This PR adds Vision Transformer (ViT) from https://arxiv.org/abs/2010.11929 as a native C++ model to the DD torch backend. 
The current implementation is adapted from https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/vision_transformer.py
Remaining functionalities to implement:

feat(ml): added vision tranformer (ViT) as torch native template

---

docker/cpu.Dockerfile
docker/gpu.Dockerfile
docker/gpu_tensorrt.Dockerfile
docker/sync_gpu_dockerfiles.sh

docker: don't install headers on gpu runtime image

---

src/CMakeLists.txt
src/backends/torch/torchdataset.cc
src/backends/torch/torchdataset.h
src/backends/torch/torchinputconns.cc
src/backends/torch/torchinputconns.h
src/backends/torch/torchlib.cc
tests/ut-torchapi.cc

~~This is placeholder PR that depends on #924  and #969 and will be rebased after these PRs have been merged.~~
It implements reading data from files. This is complicated by the dependance on input connector `DDImg` on once side and the virtual function `get_batch` from `torch::Dataset` on the other side.
EDIT: this is part of an update to `TorchDataset::get_batch` and images db support with the torch backend.

Support for torch training by reading large image datasets directly from lists of files and targets

---

CMakeLists.txt
docker/get_libs.sh
patches/xgboost/static-lib.patch

cmake was confused by external project directory that was not generated
by itself. If the external project need to be recreated it was raising
an error instead of overriding the directory.
This fixes that. But also makes the CI more robust against temporary
network issue, because cmake automatically retries if download fail,

build: don't git clone manually

---

src/backends/torch/torchdataset.cc
src/backends/torch/torchdataset.h
src/backends/torch/torchinputconns.cc
src/backends/torch/torchinputconns.h

Most important modification: avoid reading through the full db every epoch (impossibly slow on dbs with > million items), and for sequential reading in `get_batch` to avoid hd random head moves on the disk (tested with db > 800Gb).

Improvements to torch db

---

src/csvinputfileconn.cc

=> robustify in case of data passed from mem

fix(csv): remove trailing \n from header if there are any

---

src/backends/torch/torchdataset.cc
src/backends/torch/torchdataset.h
src/backends/torch/torchinputconns.cc
src/backends/torch/torchinputconns.h

This PR defaults torch db for image input connector to store encoded images instead of torch tensors. This allows a 20x compression ratio of the db size, and does not appear to affect prefetching speed while training.

feat(ml): torch db stores encoded images instead of tensors

---

CMakeLists.txt
main/dede.cc
src/oatppjsonapi.cc
src/oatppjsonapi.h

Pull request for oat-default

---

src/backends/torch/torchsolver.cc
src/backends/torch/torchsolver.h

this PR allows correct overriding of previous solver params when resuming. Previously, saved solver parameters were used, not the new ones from the  API .

fix(torch): when resume, override solver parameters after solver reload

---

src/backends/torch/native/templates/nbeats.h

last backcast output is residual error on backcast reconstruction, and thus should be encouraged to be zero

fix(nbeats): fix loss for backcast part

---

src/http/controller.hpp
src/oatppjsonapi.cc
src/oatppjsonapi.h

This is a partial implementation, HTTP 404 returned by oatpp itself are
not yet logged.
We wait 1.2.5 version of oat++ that provides a hook designed to
do access log (`responseInterceptors`).

feat: add access log for oat++

---

CMakeLists.txt
ci/Jenkinsfile.prebuilt-cache
ci/Jenkinsfile.unittests
ci/devel.Dockerfile

ubuntu 18.04 does not ship clang-format symlink for clang-format-10 by
default

ci: compile deepdetect inside a docker image

---

src/imginputfileconn.h

This fixes crashes in torch image connector when some image paths are wrong / not reachable.

fix: ddimg logger ptr

---

ci/Jenkinsfile.unittests
ci/devel.Dockerfile

This methods is slow and doesn't work well across ci nodes.
Instead we manually copy files and all nodes will have the prebuilt
cache synced by the prebuilt cache builder itself.

ci: don't use copyArtifacts

---

CMakeLists.txt
patches/pytorch/pytorch_16_new_logger.patch
patches/pytorch/pytorch_16_use_new_logger.patch
src/backends/torch/llogging.h
src/backends/torch/torchutils.h
src/backends/xgb/xgb_dmlc_macro_fix.h

This PR
-  changes implementation of CaffeLogger so that it can be used directly from classes that implement `std::ostream& operator<<(std::ostream& stream, some_class&);`  (see https://github.com/jolibrain/caffe/pull/80 for implementation of the logger only)
- simplifies _a lot_ pytorch patching, hopefully leading to much easier libtorch update to upstream (see https://github.com/jolibrain/deepdetect/pull/1086)
- should not  change its API except for accepting above usage (ie `LOG(INFO) << "message" << some_class_that_implements_above_operator_like_many_in_libtorch;`)
- should not change its behavior elsewhere in dd

refactor: make logger torch-friendly

---

src/http/controller.hpp
src/httpjsonapi.cc
src/oatppjsonapi.cc
src/oatppjsonapi.h

This replaces system_clock by steady_clock.
And includes the rapidjson/mustashe rendering within the measured duration even
its less that 1ms, just in case one day is not.

Pull request for oatpp-req-timings

---

src/backends/tensorrt/tensorrtlib.cc
src/backends/tensorrt/tensorrtlib.h

Fixes + exception if wrong batch size wrt to existing model + correctly caught exception if `enqueue` fails.

fix: ONNX tensorrt engine with correct enqueueV2

---

src/backends/tensorrt/tensorrtlib.cc
src/backends/tensorrt/tensorrtlib.h

Fixes overflow due to wrong type for `_max_workspace_size` and weird behavior with the shifted `(1<<20)` scaling.

fix: tensorrt max workspace size overflow

---

src/backends/torch/torchmodule.cc
src/backends/torch/torchutils.cc
src/backends/torch/torchutils.h

Added a function "copy_weights" to copy common weights from a
script module to a nn::Module. Weights that do not match are
ignored, and printed to the logs as warning.

feat(torch): native models can load weights from any jit file

---

src/backends/tensorrt/protoUtils.cc
src/backends/tensorrt/protoUtils.h
src/backends/tensorrt/tensorrtlib.cc
src/backends/tensorrt/tensorrtlib.h
src/backends/tensorrt/tensorrtmodel.cc
src/backends/tensorrt/tensorrtmodel.h
tests/ut-tensorrtapi.cc

TensorRT was allowing any input size, yielding to hazardous results. Since that for caffe source models, we can actually easily check the model correct size, we impose that it is equal to the requested input size. We can't do it yet for ONNX source models however.

fix: tensorrt input size for caffe source models

---

src/backends/ncnn/ncnnlib.cc
tests/ut-ncnnapi.cc

Fix NCNN bbox loop + Add datatype fp32/fp16 control to NCNN backend inference

---

src/backends/caffe/caffelib.cc
src/backends/ncnn/ncnninputconns.h
src/backends/ncnn/ncnnlib.cc

We could have `_img_sizes` in the main image data connector instead.

fix: wrong NCNN bbox output scaling

---

docs/api.md
src/backends/torch/torchlib.cc

Equivalent to the `retain_graph=True` in Pytorch.

feat(ml): retain_graph control via API for torch autograd

---

CMakeLists.txt

This is needed to build on ubuntu20.04

fix: caffe linkage with our spdlog

---

src/backends/caffe/caffeinputconns.cc

Hard read error not handled nicely by Caffe reader now throws with message and image path, e.g. image of size 0.

fix: throw if hard image read error in caffe classification input

---

src/backends/ncnn/ncnnlib.cc

Images need to be passed in memory across backends and chain actions, this was missing for NCNN.

fix: NCNN chain with images and actions

---

clients/python/dd_client/__init__.py

There was no support for `parent_id` when creating chains with the Python client.

fix: missing support for parent_id in chains with Python client

---

tests/ut-torchapi.cc

To avoid rare non deterministic fail on asserts.

chore: bump torch tests eucll assertion

---

src/backends/caffe/caffeinputconns.cc
src/backends/caffe/caffeinputconns.h
src/backends/caffe/caffelib.cc
src/backends/torch/torchdataset.cc
src/backends/torch/torchdataset.h
src/backends/torch/torchinputconns.cc
src/backends/torch/torchinputconns.h
src/backends/torch/torchlib.cc
src/backends/torch/torchlib.h
src/backends/torch/torchsolver.cc
src/backends/torch/torchsolver.h
src/backends/xgb/xgbinputconns.cc
src/backends/xgb/xgblib.cc
src/csvinputfileconn.cc
src/csvinputfileconn.h
src/csvtsinputfileconn.cc
src/csvtsinputfileconn.h
src/imginputfileconn.h
src/inputconnectorstrategy.h
src/supervisedoutputconnector.h
src/svminputfileconn.cc
src/svminputfileconn.h
src/txtinputfileconn.cc
src/txtinputfileconn.h
src/utils/fileops.hpp
src/utils/utils.hpp
tests/ut-graph.cc
tests/ut-torchapi.cc

this PR adds support for multiple test sets for torch backend.
example call:
```
data: ["path/to/train/set", "path/to/first/test/set", "path/to/second/test/set", ....]
```
support for csvts, img, txt (ie everything supported by torch mllib atm)

Multiple test sets

---

CMakeLists.txt
patches/ncnn/ncnn_cont_indic.patch
patches/ncnn/ncnn_inner_keep_h.patch
tests/CMakeLists.txt
tests/ut-ncnnapi.cc

this PR superseeds https://github.com/jolibrain/deepdetect/pull/1152
(ie it incorporates this PR1152 + fixes another issue)
this should fix https://github.com/jolibrain/deepdetect/issues/1151
issue fixed :  ncnn now uses a lot of architecture dependent optimizations , and our patch on innerproducts for keeping h dimension is implemented only for generic code thus we force generic code execution ; before this patch, data was packed for some architecture optim but generic code was called. This fix by disabling data packing for innerproduct layer
now with UT ! :)

fix(ncnn): update innerproduct so that it does not pack data

---

src/apidata.cc
src/apidata.h
src/jsonapi.cc
src/mlmodel.h
tests/ut-apidata.cc
tests/ut-conn.cc

This just uses default APIData constructors instead of have to defined
all copy/move semantics.
Instead of using the special constructor for RapidJson, we just call the
fromRapidJson() method when needed.

fix: -Werror=deprecated-copy gcc 9.3

---

src/backends/torch/torchmodule.cc

I spent a long time figuring out why my native model was returning an empty tensor, only to realize their was a `recurent.prototxt` in the repo, probably added by mistake.
This PR adds an error message to make things more explicit.

fix(torch): add error message when repository contains multiple models

---

src/txtinputfileconn.h
tests/ut-torchapi.cc

this PR fixes a bug in case of training with txt _and_ torch _and_ using explicit test set. This bug was introduced in https://github.com/jolibrain/deepdetect/pull/1095.
Also add a test case.

fix(torch/txt): correctly handle test sets in case of no splitting

---

src/backends/torch/native/templates/nbeats.h
src/backends/torch/native/templates/vit.h

This should fix the warnings. It seems like implicit move assignment operator does not trigger the warning, I think the move assignment operator is replaced by the copy assignment operator when it is not defined, hence no warning.
In C++ there are no simple ways to implement default copy constructor with user defined behavior for some class fields, if we implement the copy constructor we have to copy every parameter manually, which is error prone. For classes with many parameters like TorchMllib for example, I think we could take advantage of the default move constructor to avoid trivial mistakes, like forgetting to move one class field in the move constructor. It could be done in a future refactor.

chore(torch): define explicit assignment operators

---

src/chain_actions.cc
src/http/controller.hpp

New chain crop action parameters:
- `to_rgb` and `to_bgr` to accomodate passing crops between models that take different input formats
- `fixed_width` and `fixed_height` to allow cropping a fixed number of pixels around the original bounding box

Feat crop action new params

---

docker/cpu.Dockerfile
docker/gpu.Dockerfile

Fixes wrong permissions on `/opt/models/` in docker images that prevented all our examples in https://www.deepdetect.com/models/ from working.

fix: docker /opt/models permissions

---

src/backends/torch/optim/ranger.cc

lookahead was done in ranger even if option was set to false in parameters. This PR fixes that

fix(torch/ranger): allow not to use lookahead

---

src/backends/torch/torchdataset.cc
src/backends/torch/torchinputconns.cc
src/backends/torch/torchinputconns.h
tests/ut-torchapi.cc

this PR allows to use csvts + db
(not completely usefull combination: all csvts are read before being put into db, some more work is needed to put them into db one after the other. ATM only interesting property is to release CPU memory after putting them into db)
also add ut

fix(torch/timeseries): in case of db, correctly finalize db

---

src/backends/caffe/caffelib.cc
src/backends/caffe/caffelib.h

see side bug of https://github.com/jolibrain/deepdetect/issues/1190

fix(caffe/cudnn): force default engine option in case of cudnn not compiled in

---

ci/build-docker-images.sh

tensorrt image is a bit longer to start, so increase the waiting time

ci: increase time of dd bootup

---

tests/ut-tensorrtapi.cc

Lower working memory for TensorRT tests on Jetson nano typically.

fix: tensorrt tests on Jetson nano

---

src/backends/torch/torchlib.cc

this makes delete_service on torchlib consistent with caffelib behavior

feat(torch): save last model at training service interruption

---

docs/api.md
src/backends/torch/native/native_factory.cc
src/backends/torch/native/templates/nbeats.cc
src/backends/torch/native/templates/nbeats.h
tests/ut-torchapi.cc

this PR fixes seasonality block thanks to @mathilde-schveitzer 's work
basically, the number of function in basis was not large enough, we now put a max value as a default
we also get back to simpler linspaces definitions (ie we also fix the conversion from timesteps to values to give to functions from this basis)
exemple : 
parameters.mllib.template = "nbeats"
parameters.mllib.template_params= {"stackdef" : ["s","g8","g8","b3","h8"] }
s for 1 seasonality stack
g8 for 1 generic stack of output width 8 * _datadim (number of signals)
b3 for 3 blocks per stack
h8 : internal width of 8 * _datadim everywhere (every block contains starts with a  3 layer MLP of width 8 * _datadim in this case)

fix(nbeats): make seasonality block work

---

src/csvtsinputfileconn.cc

this (should) fix a segfault when accessing empty vals for scaling

fix(timeseries): throw if no data found

---

docs/api.md
src/backends/torch/torchlib.cc
src/backends/torch/torchlib.h
src/backends/torch/torchmodule.cc
src/backends/torch/torchmodule.h
src/backends/torch/torchutils.cc
tests/ut-torchapi.cc

at predict time, allow to change internal data representation
simply add: 
`parameters.mllib.datatype : "fp16"`
(default is fp32)
also supports fp64 (double) on cpu and gpu

feat(torch): allow FP16 inference on GPU

---

CMakeLists.txt
docs/api.md
patches/pytorch/vision/pytorch_vision_09_fasterrcnn.patch
src/backends/torch/torchdataset.cc
src/backends/torch/torchdataset.h
src/backends/torch/torchinputconns.cc
src/backends/torch/torchinputconns.h
src/backends/torch/torchlib.cc
src/backends/torch/torchlib.h
src/backends/torch/torchloss.cc
src/backends/torch/torchloss.h
src/backends/torch/torchmodule.cc
src/backends/torch/torchmodule.h
src/utils/bbox.hpp
tests/CMakeLists.txt
tests/ut-torchapi.cc
tools/torch/trace_torchvision.py

Support of Faster RCNN & RetinaNet training on CPU at batch size 1
only.
Training on GPU leads to a segfault: https://github.com/pytorch/vision/issues/3525
EDIT: Fixed by upgrading pytorch to 1.8, see #1222
Models must be traced with a modified torchvision until this bug is resolved: 
https://github.com/pytorch/vision/issues/3469
`trace_torchvision` script uses the same torchvision used to build dede, which has the necessary modification.
TODO
```bash
python3 tools/torch/trace_torchvision.py -v fasterrcnn_resnet50_fpn -o "/opt/platform/models/training/fasterrcnn_test_coco/" --num_classes 2
curl -X PUT 'http://localhost:8080/services/fasterrcnn_train' -d '{
"description": "Torch traced fasterrcnn on cars",
"model": {
"repository": …
```

feat(torch): torch detection training

---

src/chain_actions.cc

Was affecting the color conversion when detection yields multiple bboxes and crops.

fix(chains): cloning of image crops in chains

---

src/jsonapi.cc
src/jsonapi.h
tests/ut-oatpp.cc

in jsonapi, service names were forced to lower when read from json, but were not forced lower case when directly read for url (since switch to  oatppjsonapi from httpjsonapi). We now always force lower case (and thus case insentitivity) 
now with updated ut

fix: services names were not always case insensitive

---

tools/torch/trace_torchvision.py

Was actually fixed in https://github.com/jolibrain/deepdetect/pull/1265,
removed the exception in the export script

fix(torch): retinanet now trains correctly

---

src/backends/torch/torchdataaug.cc
src/backends/torch/torchdataaug.h
src/backends/torch/torchlib.cc
tests/ut-torchapi.cc

API remains unchanged wrt. caffe backend.
This also fixes:
- cutout with BW images
- cutout probability setup via API

feat(torch): image data augmentation with random geometric perspectives

---

docs/api.md
src/CMakeLists.txt
src/backends/torch/native/native_factory.cc
src/backends/torch/native/native_factory.h
src/backends/torch/native/templates/visformer.cc
src/backends/torch/native/templates/visformer.h
tests/ut-torchapi.cc

This an implementation of https://arxiv.org/pdf/2104.12533.pdf with Visformer-tiny and Visformer-S, available respectively via API:
```
"mllib":{
"template":"visformer",
"template_params": 
{
"visformer_flavor":"visformer_tiny",
"dropout": 0.1
}
}
```
Quick training results on cats/dogs yield much easier and natural convergence than with ViT, probably thanks to the removal of the lowest attention layer, staging and batch norm, as elegantly detailed in the paper.

feat(ml): Visformer architecture with torch backend

---

src/backends/torch/torchdataaug.cc
src/backends/torch/torchdataaug.h
src/backends/torch/torchdataset.cc
src/backends/torch/torchdataset.h
src/backends/torch/torchinputconns.h
src/backends/torch/torchlib.cc

This PR adds data augmentation on both images and bounding boxes for training robus object detectors with the torch backend.
There's support for mirroring, rotations and random affine transforms. Cutout is not supported at this stage, it is easy to add it. Multiple transforms can be applied sequentially.
Example augmented inputs:
It also adds the additional fix/features below:- 
- fixes a bug that had test db reader apply data augmentation at test time
- allow on-the-fly training image resizing when reading from a db created with a different image size
- fix rotation 90 vs 270 degrees,

feat(ml): data augmentation for object detection with torch backend

---

tests/ut-ncnnapi.cc

appeared at some point while reformating output from timeseries; undetected previously due to not tested in CI

fix(ncnn): fix typo in ut

---

src/apidata.cc
src/dto/input_connector.hpp
src/imginputfileconn.h
tests/CMakeLists.txt

this PR allows scale input param to be either bool for csv/csv or float for img;
this PR also includes https://github.com/jolibrain/deepdetect/pull/1277

Fix dto scale + fix ncnnapi deserialization error

---

CMakeLists.txt
patches/trt/0003-c++14.patch

this PR forces trt to compile with -std=c++14 everywhere, removes _a lot_ of deprecation warning

chore(tensorrt): update to c++ 14

---

tools/torch/trace_timm_models.py

This PR allows tracing models architectures and pretrained weights from https://github.com/rwightman/pytorch-image-models
Tested with EfficientNetV2-s, should support most if not all architectures in timm.

feat(ml): python script to trace timm vision models

---

CMakeLists.txt

Limited to tensorrt, pytorch vision will require something similar.

chore(build): do not rebuild tensorrt backend upon calling make

---

src/backends/torch/torchlib.cc

torch models where only supported at the end of the chain, this adds support for an image model whose outputs go to another model

feat(torch): support detection models in chains

---

src/backends/tensorrt/tensorrtlib.cc
src/chain.cc
src/dto/output_connector.hpp
src/unsupervisedoutputconnector.h

This feature is only available when linking with dede and does improve performances a lot especially with chains

feat(trt): add return cv::Mat instead of vector for GAN output

---

tests/ut-chain.cc

trt detection model no longer in fp16

chore: make ut_chain pass

---

src/backends/torch/torchlib.cc
tools/torch/trace_detr.py

This adds export and inference for [detr](https://github.com/facebookresearch/detr) models.
Usage:
```
python3 trace_detr.py --model-in-file /path/to/detr-r50-e632da11.pth  --no_aux_loss --path-to-detr /path/to/detr/
```
Output:

feat: DETR export and inference with torch backend

---

clients/python/README.md

Current command returns the following error when trying to install `dd_client` python client from git repository:
```
ERROR: File "setup.py" not found for legacy project dd_client from git+https://github.com/jolibrain/deepdetect.git#egg=dd_client&subdirectory=dd_client.
```
This commit contains the correct command to install  `dd_client` python client from git repository.

docs: fix pip install command from git repository

---

src/backends/torch/torchlib.cc
tools/torch/trace_yolox.py

Requires a modified version of the model available here: https://github.com/jolibrain/YOLOX/tree/jit_script
TODO:
```bash
git clone https://github.com/jolibrain/YOLOX [YOLOX_LOCATION]
cd [YOLOX_LOCATION]
git checkout jit_script
python3 tools/torch/trace_yolox.py -v yolox-s --yolox_path [YOLOX_LOCATION] -o /opt/platform/models/training/yolox_coco --weights yolox_s.pth --num_classe 80
curl -X PUT 'http://localhost:8500/services/yolox_coco' -d '{
"description": "JIT YoloX on coco dataset",
"model": {
"repository": "/opt/platform/models/training/yolox_coco/"
},
"input": {
"width":640,
"height":640,
"rgb":true
},
"mllib":{
"template":"fasterrcnn",
"gpu":true,
"gpuid":0,
"num_classes":80
},
"output": {
"bbox": true
}
},
"mltype": …
```

feat: add yolox export script for training and inference

---

src/mlmodel.h

Sometimes the directory may not exist, often I'm doing silly stuff like `chmod` and then I realise that it doesn't exist..

chore: provide a more accurate error message for model directory write/exists

---

src/simsearch.cc

This is a fix to #1368 that removes MMAP when reloading an existing faiss index. This potentially impacts working with very large indexes that do not fit in RAM, but none of the other potential fixes, including disabling faiss prefetching, did work.
Related issue: https://github.com/facebookresearch/faiss/issues/1540

fix: simsearch ivf index craft after reload, disabling mmap

---

docs/source.md

- `libspdlog-dev` is not required and fails the torch+cuda builds on 20.04, it's built by default by the DD build, we can remove it
- missing dependencies on tests and standard torch build.

chore: source doc requirements update

---

src/backends/torch/torchdataset.h

Default is now to shuffle image datasets when training with torch. 
In this configuration it's not possible to undo it via API. I don't believe it's an issue though?
Note that there are two shuffling phases: one a dataset creation, the other at every epoch, but they are governed by the same boolean in `TorchDataset`. That is fine I believe.

fix: torch train shuffles image dataset by default

---

src/backends/torch/torchdataaug.cc
src/backends/torch/torchdataaug.h
src/backends/torch/torchdataset.cc
src/backends/torch/torchdataset.h
tests/ut-torchapi.cc

This PR brings:
- basic data augmentation (rotation, cutout, perspectives) to segmentation with torch
- swapped jpg compression (quality 100) to png with compression 0, as jpg was corrupting the segmentation masks (even with quality set to 100...)

feat: data augmentation for training segmentation models with torch backend

---

src/jsonapi.cc

`model.json` was overriden by the saving (wrongly) of the training call JSON return string.

fix: model.json file saving

---

docs/api.md
src/backends/torch/torchlib.cc
src/backends/torch/torchmodel.cc
src/backends/torch/torchmodel.h
src/jsonapi.cc
src/mlservice.h
tests/ut-caffeapi.cc
tests/ut-torchapi.cc
tests/ut-xgbapi.cc

This PR fixes the publishing of models and their config files.
- bug: model.json file was overriden with config.json content
- fix: config.json was optional and there's no reason for it
- when publishing a model, config.json is not written down since it is instead copied from the source model repository
- async training jobs now correctly report as training
- When using random cropping, the model size is that of the crop size. Publishing a model requires the `config.json` file to be updated. This PR introduces a placeholder for these changes, starting with the crop fix and the db flag value, but it is generic to other, possibly forthcoming config update requirements.
- fileops in file replacement was buggy and the call has been removed.

fix: torch model published config file

---

demo/objdetect/README.md
demo/objdetect/chaindetect.py
demo/objdetect/dd_client.py
src/chain.cc
src/chain_actions.cc
src/chain_actions.h
src/dto/chain.hpp
src/dto/ddtypes.cc
src/dto/ddtypes.hpp
src/services.h
src/utils/oatpp.cc
tests/ut-chain.cc

This PR opens the possibility for chains to have trailing actions.
Example chain call:
```json
{
"chain":{
"calls":[
{
"parameters":{
"input":{
"keep_orig":true,
"connector":"image"
},
"output":{
"confidence_threshold":0.5,
"bbox":true
},
"mllib":{
"net":{
"test_batch_size":2
}
}
},
"service":"detect",
"data":[
"/opt/platform/data/image.jpg"
]
},
{
"id":"face_detection_bbox",
"action":{
"parameters":{
"output_images":true,
"write_prob":true
},
"type":"draw_bbox"
}
}
]
}
}
```

feat(chain): add action to draw bboxes as trailing action

---

src/backends/torch/torchdataset.cc

It may not work with faster-rcnn.

feat: allow pure negative samples for training object detectors with torch

---

ci/devel-trt.Dockerfile

possible bug with trt tests on nep5 : incorrect specification of cuda_arch

Opencv cuda arch in dockerfile

---

.mergify.yml

Semantic PR service down since April 15th
https://github.com/zeke/semantic-pull-requests/issues/183
We can replace it by github actions or another service.

fix: remove semantic commit check

---

CMakeLists.txt
patches/trt/0011-fix_plugin_makefile_cub.patch

Note: tests are off atm for nano, so here we make sure it still works for regular trt builds.

fix: missing path to cub headers in tensorrt-oss build for jetson nano

---

src/dto/predict_out.hpp

Required when including "predict_out.hpp" alone in an external application

fix: add missing headers in predict_out.hpp

---

src/CMakeLists.txt
src/backends/torch/native/native_factory.cc
src/backends/torch/native/native_factory.h
src/backends/torch/native/templates/crnn.cc
src/backends/torch/native/templates/crnn.hpp
src/backends/torch/native/templates/crnn_head.cc
src/backends/torch/native/templates/crnn_head.hpp
src/backends/torch/torchinputconns.h
src/backends/torch/torchlib.cc
src/backends/torch/torchmodule.cc
src/backends/torch/torchmodule.h
src/dto/mllib.hpp
tests/ut-torchapi.cc

Add native resnet template from 
https://github.com/clovaai/deep-text-recognition-benchmark
https://arxiv.org/abs/1904.01906
https://arxiv.org/abs/1709.02054
```bash
curl -X POST http://localhost:8080/services/ocr '{
"description": "ocr",
"type": "supervised",
"input": {
"width": 220,
"height": 136,
"bw": false,
"db": true,
"ctc": true
},
"mllib": {
"template": "crnn",
"gpu": true,
"gpuid": 0,
"timesteps": 128,
"template_parameters": {
"hidden_size": 512,
"num_layers": 3,
"bidirectional": true,
"backbone": "resnet"
}
},
"output": {
"store_config": true
}
},
"model": {
"repository": "/opt/platform/models/training/ocr_resnet_native/",
"create_repository": true
}
}'
curl -X POST http://localhost:8080/train/ -d '{
"service": "ocr", …
```

feat: add crnn resnet native template

---

clients/python/tox.ini
src/backends/torch/torchinputconns.cc
src/backends/torch/torchinputconns.h
src/backends/torch/torchlib.cc
src/backends/torch/torchutils.cc
tests/ut-torchapi.cc

- Fix inference with OCR native model when recreating the service from a trained model repo.
- Fix a bug affecting all native models: buffers were not reloaded when recreating the service (mostly affecting models with batch norms)

fix(torch): OCR predict with native model

---

tools/torch/trace_yolox.py

Specifying number of classes, img size, checkpoint... is no longer required:
```
python3 trace_yolox.py -v yolox[-s|-m|-l|...] --yolox_path [YOLOX_PATH] --output_dir [OUTPUT_DIR] --from_repo [DD_REPO] --to_onnx
```

feat(yolox): export directly from trained dd repo to onnx

---

src/simsearch.cc

```
...
#26 1.876 [ 76%] Building CXX object src/CMakeFiles/ddetect.dir/commandlineapi.cc.o
#26 1.876 [ 76%] Building CXX object src/CMakeFiles/ddetect.dir/backends/xgb/xgblib.cc.o
#26 1.876 [ 77%] Building CXX object src/CMakeFiles/ddetect.dir/backends/xgb/xgbmodel.cc.o
#26 1.877 [ 78%] Building CXX object src/CMakeFiles/ddetect.dir/backends/xgb/xgbinputconns.cc.o
#26 1.878 [ 79%] Building CXX object src/CMakeFiles/ddetect.dir/backends/tsne/tsneinputconns.cc.o
#26 1.879 [ 79%] Building CXX object src/CMakeFiles/ddetect.dir/backends/tsne/tsnelib.cc.o
#26 1.879 [ 80%] Building CXX object src/CMakeFiles/ddetect.dir/simsearch.cc.o
#26 1.880 [ 81%] Building CXX object src/CMakeFiles/ddetect.dir/backends/torch/torchlib.cc.o
#26 1.881 In file included from …
```

chore: ignore faiss warnings

---

src/backends/torch/torchdataset.cc
src/backends/torch/torchinputconns.cc

process entries in parallel and reorder just before insertion into vector or db

chore(torch): speedup dataset creation for bbox case

---

src/backends/torch/torchlib.cc

an empty metrics field breaks the platform, and metrics field remains empty when the training is stopped early

fix(torch): add measures to output event when training not done

---

CMakeLists.txt

An incompatibility with `fmt` requires rebasing the third party lib to an earlier version (error similar to https://github.com/fmtlib/fmt/issues/1957).
Local build did pass for me, along with tests.

chore: to libtorch2 and beyond

---

src/backends/torch/torchlib.cc
src/backends/torch/torchlib.h
src/supervisedoutputconnector.h
tests/ut-torchapi.cc

TODO
For example, to request mAP with IoU threshold = 0.9: add `"map-90"` to `parameters.output.measure`.
`"map"` is no longer required if `"map-xx"` is specified, but it is kept for backward compatibility. It corresponds to a default IoU threshold of 0.5.
```bash
curl -X GET localhost:8080 -d '{
"service": "detection",
"async": true,
"input": {
},
"mllib": {
"gpu": true,
"gpuid": 2,
"net": {
"batch_size": 8,
"test_batch_size": 4
},
"solver": {
"solver_type": "ADAM"
},
"bbox": true
},
"output": {
"measure": [
"map-50", "map-75", "map-90"
],
"target_repository": ""
}
},
"data": [
"/opt/platform/data/train.txt",
"/opt/platform/data/test.txt"
]
}'
```
Example measure output:
-  `"map"` is the mean over all thresholds
```json
{
"measure": {
"test_id": 0,
"map": …
```

feat(torch): add map metrics with arbitrary iou threshold

---

CMakeLists.txt
ci/devel-trt.Dockerfile
ci/devel.Dockerfile
docker/gpu_tensorrt.Dockerfile
docs/api.md
src/backends/tensorrt/tensorrtlib.cc
src/backends/tensorrt/tensorrtlib.h
src/backends/torch/llogging.h
src/backends/torch/native/native_wrapper.h
src/backends/torch/torchlib.cc
src/backends/torch/torchlib.h
src/dto/mllib.hpp
src/utils/utils.hpp
tests/ut-chain.cc
tests/ut-tensorrtapi.cc

Added new torchlib service param `concurrent_predict` (default true) to help manage GPU memory if multiple external API callers are in use and memory management cannot be done externally.
This is in reference to [this conversation](https://matrix.to/#/!rkhGyFNrjfeCIXnDnS:gitter.im/$iKc-UQ33lWc3JOKXpzVWWGYGZkGjKCXeREijK0h3NKE?via=gitter.im&via=matrix.org) around torch concurrent predict calls and GPU memory usage management.

Added new torchlib service param `concurrent_predict`

---

src/dto/ddtypes.cc
src/dto/ddtypes.hpp
src/dto/predict_out.hpp
src/unsupervisedoutputconnector.h
src/utils/oatpp.cc
tests/ut-tensorrtapi.cc
tests/ut-torchapi.cc

With `image=true`, a dd predict call will now return base64 encoded images in an `images` field.
Adds `parameters.output.encoding`: an extension characterizing the image encoding, e.g ".png" or ".jpg"

feat: allow returning images in json in base64 format

---

src/apidata.cc
src/apidata.h
src/backends/tensorrt/tensorrtlib.cc
src/backends/tensorrt/tensorrtlib.h
src/chain.cc
src/chain_actions.cc
src/chain_actions.h
src/dd_types.h
src/dto/predict_out.hpp
src/jsonapi.cc
src/services.h
src/utils/oatpp.cc
src/utils/oatpp.hpp
src/utils/utils.hpp
tests/ut-chain.cc

Adds a "recompose" action at the end of a chain to replace a part of an image (determined by a detection model) with a transformed version created by a generative model.
Example: Given 2 services "detection" and "gan"
```bash
curl -X POST localhost:8080/chain -d '{
"chain": {
"name": "chain",
"calls": [
{
"service": "detection",
"input": {
"keep_orig": true,
"cuda": true
},
"output": {
"bbox": true,
"best_bbox": 2
}
},
"data": [
"examples/trt/cyclegan_resnet_attn_onnx_trt/horse_1024.jpg"
]
},
{
"id": "crop",
"action": {
"type": "crop",
"fixed_width": 360,
"fixed_height": 360
}
}
},
{
"service": "gan",
"parent_id": "crop",
"input": {
"cuda": true
},
"mllib": {
"extract_layer": "last"
},
"output": {
"image": true
}
}
},
{
"id": "recompose", …
```

feat: recompose action to recreate an image from a GAN + crop

---

CMakeLists.txt
patches/pytorch/pytorch_23_cloneable.patch
patches/pytorch/pytorch_23_use_new_logger.patch
src/apidata.h
src/backends/torch/optim/madgrad.cc
src/backends/torch/optim/radam.cc
src/backends/torch/optim/ranger.cc

<!>
- Added hard coded system mpi includes because they were not found by CMake -> maybe there's an other way around ?
- torch::nn::Cloneable is no longer a virtual class, which breaks most native modules in dede. I chose to revert the change with a patch, which might not be the best solution long-term wise

chore: update pytorch to 2.3

---

src/backends/torch/torchlib.cc

Rotate augments with non square images will fail silently.

chore: add warning when trying to rotate non-square images

---

src/backends/torch/torchlib.cc

`torch::argmax` was done on batch dimension instead of classes dimension.
`segmap` tensor had shape `height*width` instead of `test_batch_size*height*width`.
This resulted in bad metrics and segfaults.
Maybe we should do the same here: https://github.com/jolibrain/deepdetect/blob/master/src/backends/torch/torchlib.cc#L1858

fix(torch): segmentation with test_batch_size > 1

---

CMakeLists.txt
README.md
docs/api_swagger.md
src/CMakeLists.txt
src/dd_config.cc.in
src/dd_config.h.in
src/http/controller.hpp
src/http/documentation.cc
src/http/documentation.hpp
src/http/swagger_component.hpp

Swagger documentation is served by the DeepDetect server at `host:port/swagger/ui`
Open API json is also served by the server at `host:port/api-docs/oas-3.0.0.json`. It can be used to serve documentation as a separate page, for example with Fast API.
To serve the documentation as a static page, the required files are:
```
/api-docs/oas-3.0.0.json
/swagger/favicon-16x16.png
/swagger/ui
/swagger/swagger-ui.css
/swagger/swagger-ui-bundle.js
/swagger/swagger-ui-standalone-preset.js
```

Swagger api doc

---

src/backends/torch/torchlib.cc
src/dto/mllib.hpp

Add a parameter to change (application wise) jit fusion strategy. May help when the models takes several minutes to compile. default is static = 2 and dynamic = 10, to lower compile time, set them to lower values (?)

feat(torch): add JIT FusionStrategy selection

---

src/CMakeLists.txt
src/backends/torch/torchlib.cc
src/backends/torch/torchmodule.cc
src/backends/torch/torchmodule.h
src/utils/rectangular_lsap.cpp
src/utils/rectangular_lsap.h
tests/CMakeLists.txt
tests/ut-torchapi.cc
tools/torch/trace_detr.py
tools/torch/trace_rtdetrv2.py

To use with this DETR branch: https://github.com/jolibrain/detr/tree/jit_script
```
git clone -b jit_script git@github.com:jolibrain/detr.git
wget https://dl.fbaipublicfiles.com/detr/detr-r50-e632da11.pth
...
python3 trace_detr.py --path-to-detr ~/detr --num_classes 2 --model-in-file ~/detr-r50-e632da11.pth
```
Or with this RT-DETR branch: https://github.com/jolibrain/RT-DETR/tree/jit_script
```
git clone -b jit_script git@github.com:jolibrain/RT-DETR.git
wget https://github.com/lyuwenyu/storage/releases/download/v0.2/rtdetrv2_r18vd_120e_coco_rerun_48.1.pth
...
python3 trace_rtdetrv2.py --path-to-rtdetrv2 ~/RT-DETR/rtdetrv2_pytorch/ --num_classes 2 --model-in-file ~/rtdetrv2_r18vd_120e_coco_rerun_48.1.pth rtdetrv2_s
```
To create the service:
```
{
"input": {
"connector": …
```

feat: enable DETR and RT-DETRv2 training

---

src/backends/torch/torchlib.cc

output has shape (N, C, H, W)
when N was 1, squeeze() removed the first dimension and we did the argmax on the wrong dimension

fix(torch): segmentation with test_batch_size 1
