src/caffelib.cc
src/httpjsonapi.cc
src/txtinputfileconn.cc
src/txtinputfileconn.h

Eases classification from large datasets of sentences, such as tweets or URLs. This can be used with parameter `sentences:True` passed to input txt connector. The data repository needs to be structured such that there's a repository per class, and a text file per class repository, that contains all `\n` separated sentences for that class.

Sentences classification with Text connector

---

clients/python/dd_client.py

Hi beniz,
I have created the client Api code compatible with python3 and python2 both. Have a look at it.

making client API compatible with python3

---

README.md
demo/imgsearch/README.md
demo/imgsearch/dd_client.py
demo/imgsearch/imgsearch.py

See https://github.com/beniz/deepdetect/tree/imgsearch/demo/imgsearch and the instructions in the README file.

Example of image similarity search with both indexing and searching, based on Deep Convolutional Net

---

demo/imgdetect/index.html
demo/imgdetect/js/main.js

Frontend is listing the services available on dd server.
User won't be able to upload an image if not service is available.
User are able to select the service to use during the image classification process.
Solves issue #95

Add service selector on image classification frontend

---

CMakeLists.txt
main/CMakeLists.txt
tests/CMakeLists.txt

Tested with both OpenCV 2 and 3 on Ubuntu 14.04.

build support for both OpenCV 2 and 3, including Caffe, ref #36

---

src/supervisedoutputconnector.h
tests/ut-conn.cc

New cmfull output format + unit test

---

src/httpjsonapi.cc

Access logs in Common Log Format, see #203 
Sample:
```
INFO - 16:55:18 - 127.0.0.1 "PUT /services/imageserv" 201
ERROR - 16:55:20 - 127.0.0.1 "PUT /services/imageserv" 403
INFO - 16:55:22 - 127.0.0.1 "GET /info" 200
INFO - 16:55:27 - 127.0.0.1 "POST /predict" 200 2884
```

support for API access logs in CLF, ref #203

---

src/imginputfileconn.h
src/txtinputfileconn.h

Fixes compatibility with gcc6

---

src/caffelib.cc

Fixes number of classes `prototxt` update when using sparse logistic regression.

Number of classes fix in sparse logistic regression for #215 #216

---

src/supervisedoutputconnector.h

Probably a better solution for #219 than #220  (you can choose :) )

Fix _best overwritten by bbox

---

demo/imgdetect/js/main.js

```data.body.predictions``` is now an array, correct the code accordingly.

Fix issue on imgdetect #244

---

src/xgblib.cc

New supported parameters, following https://github.com/dmlc/xgboost/blob/master/doc/parameter.md

update to XGBoost parameters via API, ref #249

---

ISSUE_TEMPLATE.md

Hello!
As requested (a long, long time ago ;) ), here is the PR for the issue template.
This template could be stored in the .github/ directory too.
R.

Added issue template in the root directory.

---

src/caffelib.cc
src/caffelib.h

This PR fixes multi-GPU training support for the Caffe backend.

Full support for Multi-GPUs training with Caffe backend

---

src/caffeinputconns.cc
src/caffeinputconns.h
src/caffelib.cc
src/caffelib.h
src/imginputfileconn.h

Cropping at training time with Caffe was prone to network size errors.

Fixed cropping and network size changes with Caffe

---

clients/python/dd_bench.py
clients/python/dd_client.py

I have made update for `dd_client` using python library **[Requests](https://github.com/kennethreitz/requests)**.  
Now there is better readability and exception handling (see more here [Requests - Errors and Exceptions](http://docs.python-requests.org/en/master/user/quickstart/#errors-and-exceptions))
Also there is difference in `return types` in `dd_client`:  
**Before:**  
- flag `RETURN_PYTHON` -> return **json** object
- flag `RETURN_JSON` -> return **string** object  
**Now:**
- flag `RETURN_JSON` -> return **json** object
- flag `RETURN_TEXT` -> return **string** object  
- flag `RETURN_PYTHON` doesn't exist anymore
I have executed unitises in python binding for DeepDetect **[pyDD](https://github.com/ArdalanM/pyDD/tree/dev/pydd)**, all tests passed.

Python dd_client

---

src/csvinputfileconn.cc

CSV pre-processing: non numerical inputs undeclared as categorical or ignored now yields an error

---

.travis.yml
CMakeLists.txt
cmake/Cuda.cmake

Add Travis, fix eigen3  
remove unnecessary changes in #276 
Regression test on 16.04 == PASS

add Travis, fix regression issue caused by #276

---

README.md

fix vgg19 link in readme

---

clients/python/dd_bench.py

add service creation option in dd_bench.py
usage
--create [model's folder name]
--nclasses [number of classes; default to 1000]
--auto-kill 
This options are for pre-trained NN.
Meant to streamline the benchmarking process.
Invocation of the server is still required. 
--auto-kill  would allow the user to change the models easily without manually killing the service

add service creation option in dd_bench.py

---

demo/tsne/demo_tsne_txt.py
src/jsonapi.cc
src/services.h
src/tsneinputconns.cc
src/tsneinputconns.h
src/tsnelib.cc

Reads text files and reduces them to 2D clusters with TSNE.

TSNE from text data

---

src/txtinputfileconn.cc
src/txtinputfileconn.h

Detecting directory of data when training from text, allowing test set detection

---

src/caffeinputconns.h
src/txtinputfileconn.h

Forcing shuffle on text and images with Caffe backend

---

src/caffelib.cc

See https://github.com/beniz/caffe/pull/6 for the PR to our custom Caffe.
This is the implementation of "On the convergence of Adam and beyond" 
https://openreview.net/forum?id=ryQu7f-RZ

Added support for Amsgrad optimizer (fix to Adam)

---

demo/objsearch/model/deploy.prototxt
demo/objsearch/objsearch.py
demo/objsearch/objsearch_dd.py
src/simsearch.cc
src/simsearch.h
src/supervisedoutputconnector.h
src/unsupervisedoutputconnector.h
tests/CMakeLists.txt
tests/ut-simsearch.cc

Brings object detection output regions of interest (ROI) to the built-in similarity search engine.
Output is multiple similar objects per predicted object bounding box, along with category, probability and distance.
Overall this is a DD side full C++ alternative to the `demo/objsearch` Python code.

Built-in image object detection and similarity search

---

README.md

TODO : add https://deepdetect.com/models/inception/inception_bn_21k as download link for this model

 added inception21K model to README.md

---

.travis/build.sh
src/xgblib.cc

Changes introduced by XGBoost commit d5992dd88101abf2345095181504d003b4fc2c04 / issue https://github.com/dmlc/xgboost/pull/3116

fixed xgboost back-end

---

src/caffelib.cc
templates/caffe/enet/deploy.prototxt
templates/caffe/enet/enet.prototxt
templates/caffe/enet/enet_solver.prototxt

This is the template for ENet, https://arxiv.org/abs/1606.02147
Modified from https://github.com/TimoSaemann/ENet
Note:
- we're not using spatial dropout

Support for ENet / embedded semantic segmentation net

---

src/supervisedoutputconnector.h
tests/ut-conn.cc

but still complexity is in nclasses^2 which makes it very long for very large number of labels

much better distance correlation, do not saturate ram

---

src/xgbinputconns.cc
src/xgblib.cc

Due to XGBoost commit ccf80703efefc7c9ff988c454c05e01beacba26d

fixed xgboost build due to xgboost C++ data structure changes

---

CMakeLists.txt
README.md
main/CMakeLists.txt
src/caffeinputconns.cc
src/caffeinputconns.h
src/caffelib.cc
src/caffelib.h
src/mlmodel.h
src/supervisedoutputconnector.h
templates/caffe/crnn/crnn.prototxt
templates/caffe/crnn/crnn_solver.prototxt
templates/caffe/crnn/deploy.prototxt
tests/CMakeLists.txt

This PR brings full support to OCR training.
Features:
- CRNN template for CNN+LSTM with CTC loss
- training via DD API with hdf5 database backend
- training accuracy via CTC loss from within the Caffe network
Dataset format:
- text file with all images and OCR labels as follows:
```
/path/to/img.jpg this is what is written on the image
```
Usage:
- service creation uses the newly introduced `ctc` boolean flag:
```
curl -X PUT "http://localhost:8080/services/ocrservice" -d '{
"mllib":"caffe",
"description":"OCR service",
"parameters":{
"input":{                                  
"connector":"image", 
"ctc":true,
"width":160,
"height":60
},          
"mllib":{
"template":"crnn",
"nclasses":11
} …
```

OCR training with CTC-CNN+LSTM

---

src/supervisedoutputconnector.h

distance correlation is not eigened, I am not sure it can be parallelized, will do different pull request if so

eigen version of multi label soft proba metrics

---

src/supervisedoutputconnector.h
tests/ut-conn.cc

generalize previous no_0
if measure is given as precedently, (eg "kl"), no change -> outputs kl and kl_no_0
added ability to give kl-0.1  which discards from evaluation every prediction whose target has value <= 0.1
so "kl-0" is equivalent to "kl"

Multi label regression threshold

---

src/backends/caffe/caffelib.cc

fixed rotate and mirror options with dense image processing / segmentation

---

src/backends/caffe/caffelib.cc
src/backends/caffe/caffelib.h
src/backends/tf/tflib.cc
src/backends/xgb/xgblib.cc
src/mllibstrategy.h
src/mlservice.h

Specifies the type of the service, e.g. regression, classification, detection, segmentation, ctc, ...

added mltype variable to GET /info and GET /services calls.

---

CMakeLists.txt
src/backends/caffe/caffelib.cc

data augmentation support for images stored in hdf5 databases with caffe

---

src/mlservice.h

Added creation parameters to GET /service output, ref #446

---

src/backends/caffe2/caffe2lib.cc
src/backends/caffe2/caffe2libstate.h
src/jsonapi.cc
src/services.h
tests/ut-caffe2api.cc

```
curl -X PUT "http://localhost:8080/services/imageserv" -d '{
"mllib":"caffe2",
"description":"image classification service",
"type":"unsupervised",
"parameters":{
"input":{
"connector":"image"
}
},
"model":{
"repository":"$PATH_TO_AN_EXISTING_DIRECTORY"
}
}'
```
```
curl -X POST "http://localhost:8080/predict" -d '{
"service":"imageserv",
"parameters":{
"input":{
"width":224,
"height":224
},
"mllib":{
"extract_layer": $NAME_OF_A_LAYER
}
},
"data":["http://i.ytimg.com/vi/0vxOhd4qlnA/maxresdefault.jpg"]
}'
```
You can test with:
model : https://github.com/caffe2/models/tree/master/resnet50
extract layer : ```gpu_0/res2_0_branch2c```

Caffe2 unsupervised predict

---

src/supervisedoutputconnector.h

add per class map computation, added to the results 
(so the "m" is "mean" over images, whereas in standard definition, it is "mean" over classes)

add per class map

---

src/backends/caffe/caffemodel.cc
src/backends/caffe/caffemodel.h
src/mlmodel.h
src/mlservice.h
src/utils/fileops.hpp
tests/ut-jsonapi.cc

create directory for repository if it does not exist
makes sense only in conjunction with "template" parameter 
```
curl -X PUT "http://localhost:9999/services/calibration" -d '{
"mllib":"caffe",
"description":"clothes calibration",
"type":"unsupervised",
"parameters":{
"input":{
"connector":"image",
"height":300,
"width":300
},
"mllib":{
"nclasses":1000, "template": "resnet_50"
}
},
"model":{
"repository":"/home/infantes/test/calibration",
"create_repository": true
}
}'
```

Mkdir repo

---

CMakeLists.txt
patches/caffe2/eigen.patch

changed PYTORCH_SUPPORTED_COMMIT hash in CMakeLists.txt

Switched to pytorch v0.4.0

---

src/supervisedoutputconnector.h

correct stringstream use for delta_score name output

---

CMakeLists.txt
src/httpjsonapi.cc
src/httpjsonapi.h
tests/ut-httpapi.cc

previously 2 http options of the form  a.b.c=d and a.b.e=f were generating a json structure 
as {a:{b:{c:d}},a:{b:{e:f}}}   which is BAD
we are now generating
{a:{b:{c:d,e:f}}} which is GOOD

Debug httpjsonapi

---

src/mllibstrategy.h
src/services.h
src/utils/fileops.hpp
tests/ut-jsonapi.cc

curl -X DELETE http://host:port/services/sname?clear=dir   also deletes repository, whereas
curl -X DELETE http://host:port/services/sname?clear=full deleted only content of repository

add possibility to remove dir (aka clear=dir)

---

src/backends/caffe/caffelib.cc
src/backends/caffe/caffelib.h
src/supervisedoutputconnector.h

Fixed: 
- mAP metric collect does ot depend on batch size
- AP per class metric name fix
- compilation warnings

fixes to SSD training metrics

---

CMakeLists.txt
src/backends/caffe/caffelib.cc
src/backends/caffe/caffelib.h

during model training, create a file in repo named `best_model` that contains:
- best iteration number,
- corresponding metric and value
- model (forced snapshot when required)

Save best value of metric and iteration number

---

src/backends/caffe/caffeinputconns.cc
src/backends/caffe/caffeinputconns.h
src/backends/caffe/caffelib.cc

+  mean values fix in `deploy.prototxt`

Added support for db_width and db_height to force resize the db images with SSD

---

src/jsonapi.cc
src/jsonapi.h
tests/ut-jsonapi.cc

Improvement to the JSON error reports, now includes the same error log string as reported by the server, in most cases.

JSON error report improvement

---

src/backends/caffe/caffelib.cc
src/backends/caffe/caffelib.h
src/backends/caffe/caffemodel.cc
src/backends/caffe/caffemodel.h
src/mlmodel.h
tests/ut-caffeapi.cc

This PR adds a simple form of model publication once training has completed. Useful for moving the models onto production / prediction setup automatically once training has completed.

`target_repository` allows automatic copy of best model to target directory

---

examples/caffe2/detectron/README.md
src/backends/caffe2/caffe2inputconns.h
src/backends/caffe2/caffe2inputimg.cc
src/backends/caffe2/caffe2inputinterface.cc
src/backends/caffe2/caffe2lib.cc
src/backends/caffe2/caffe2lib.h
src/backends/caffe2/caffe2libstate.h
src/backends/caffe2/caffe2model.cc
src/backends/caffe2/nettools.h
src/backends/caffe2/nettools/debug.cc
src/backends/caffe2/nettools/devices_and_operators.cc
src/backends/caffe2/nettools/fillers_and_optimizers.cc
src/backends/caffe2/nettools/gradients.cc
src/backends/caffe2/nettools/internal.cc
src/backends/caffe2/nettools/internal.h
src/backends/caffe2/nettools/workspace_and_nets.cc
src/imginputfileconn.h
src/utils/apitools.h
tests/CMakeLists.txt
tests/ut-caffe2api.cc

Added support for Detectron models (prediction only)
See https://github.com/chichaj/deepdetect/tree/detectron_predict/examples/caffe2/detectron

Added detectron support

---

src/backends/caffe/caffelib.cc
src/supervisedoutputconnector.h

This PR adds multibox aggregation similarity search for images. Introduces the `output` API flag `multisearch_rois`.

added support for multibox rois search

---

src/backends/caffe/caffeinputconns.cc
src/backends/caffe/caffeinputconns.h
src/backends/caffe/caffelib.cc
src/backends/caffe/caffelib.h
src/generators/net_caffe.cc
src/generators/net_caffe.h
src/generators/net_caffe_convnet.cc
src/generators/net_caffe_convnet.h
src/generators/net_caffe_mlp.cc
src/generators/net_caffe_resnet.cc
src/generators/net_caffe_resnet.h
src/supervisedoutputconnector.h
tests/ut-caffe-mlp.cc
tests/ut-caffeapi.cc

Support for convolutional autoencoder on images, including:
- Deconvolution neural net generator layer
- Upsampling neural net generator layer
- Hourglass architectures with control from API

CNN autoencoder support for Caffe backend

---

CMakeLists.txt
src/backends/caffe/caffelib.cc
tests/ut-caffe-mlp.cc
tests/ut-caffeapi.cc

in caffe connector, like noise and distort
```
'mllib': { ..., 'geometry': {'all_effects':false, 'persp_horizontal':true, 'persp_vertical':false, 'zoom_in':true, 'zoom_out':true', 'persp_factor':0.2, 'zoom_factor':0.1, 'pad_mode':'mirrored', 'prob':0.1} ... }
```
warning: this branch also contains cnn_autoenc and thus should be merge after 
this branch needs 'perspective transform branch from caffe'

Perspective transform : dede options

---

CMakeLists.txt
examples/caffe2/detectron/README.md
examples/caffe2/detectron/convert_pkl_to_mask_net.py
examples/caffe2/detectron/generate_coco_corresp_file.py
examples/caffe2/detectron/masks.md
examples/caffe2/detectron/plot_masks.py
patches/caffe2/collect_proposals.patch
patches/caffe2/custom_ops/bbox_to_roi_op.cc
patches/caffe2/custom_ops/bbox_to_roi_op.h
patches/caffe2/custom_ops/multi_level_roi_op.cc
patches/caffe2/custom_ops/multi_level_roi_op.h
patches/caffe2/custom_ops/segment_mask_op.cc
patches/caffe2/custom_ops/segment_mask_op.h
src/CMakeLists.txt
src/backends/caffe2/caffe2inputimg.cc
src/backends/caffe2/caffe2lib.cc
src/backends/caffe2/caffe2lib.h
src/backends/caffe2/caffe2libstate.h
src/backends/caffe2/caffe2model.cc
src/backends/caffe2/caffe2model.h
src/backends/caffe2/nettools.h
src/backends/caffe2/nettools/debug.cc
src/backends/caffe2/nettools/devices_and_operators.cc
src/backends/caffe2/nettools/netgroup.cc
src/backends/caffe2/nettools/workspace_and_nets.cc
src/supervisedoutputconnector.h
tests/CMakeLists.txt
tests/ut-caffe2api.cc

Added a ```'mask': true``` flag.
More detail in the [README.md](https://github.com/chichaj/deepdetect/tree/detectron_mask/examples/caffe2/detectron)
A complete example in the [masks.md](https://github.com/chichaj/deepdetect/tree/detectron_mask/examples/caffe2/detectron/masks.md)

Added mask support for detectron models

---

src/backends/caffe/caffelib.cc
src/backends/caffe2/caffe2lib.cc
src/jsonapi.cc

previously template="" was acting trying to instantiate template with empty name. Now template="" does not try to instantiate template.

make template='' behave like no template

---

Jenkinsfile

Jenkins chat notify

---

src/backends/caffe/caffelib.cc
src/backends/caffe2/caffe2lib.cc
src/jsonapi.cc
src/jsonapi.h
src/mllibstrategy.h
src/mlservice.h
tests/ut-caffe2api.cc

Also `metrics.json` now always written on disk.  This is useful on the platform across resume.

Training metrics preservation across resume calls.

---

src/backends/caffe/caffelib.cc

correctlty set default of boolean conf_best so that it best confidence map is not output by default

fix : do not output best confidence map if not asked for 

---

CMakeLists.txt
src/backends/ncnn/ncnninputconns.h
src/backends/ncnn/ncnnlib.cc

This allows running OCR models on raspberry pi, and other embedded devices.

Support for CTC to NCNN backend

---

src/backends/ncnn/ncnnlib.cc
src/backends/ncnn/ncnnlib.h

This allows reporting the model type to the platform.

NCNN model type for using with the platform

---

src/mlmodel.h

Similarity search index preloading is off as default value.

fixed index_preload default

---

src/jsonapi.cc
src/jsonapi.h
src/mlservice.h

Shared variable led to mixed up metrics in `metrics.json`

Fixed resuming of metrics

---

src/backends/caffe/caffelib.cc
src/backends/caffe/caffelib.h
src/mllibstrategy.h
src/mlservice.h

add some model stats in output json, 
ie 
body 
-> 
stats |  
-> data_mem_train | 4418640068
-> data_mem_test | 1104660048
-> params | 26027072
-> flops | 3858497408
where data_mem train is the memory needed for data during training (sum of top blobs  : does not include network params neither original raw data)
data_mem_test is the memory needed for data during test phase
params is the number of parameters of the model 
flops is the estimated number of operations needed for inference

output some stats in status json

---

src/backends/caffe/caffelib.cc

fix for taking into account dice that takes flat (non multiplexed) labels
needs to merge first both
- https://github.com/jolibrain/caffe/pull/43
- https://github.com/jolibrain/caffe/pull/44

dice perfo fix 

---

src/backends/ncnn/ncnnlib.cc

not sure old_height was correctly initialized

FIX: small glitch in init, was ok before, but clearer now

---

CMakeLists.txt

change CMakeList to compile dede against openCV 3 or 2, but do not try OpenCV 4, as there are a lot of API changes

check for openCV 2 or 3, but not 4

---

clients/python/dd_bench.py

new options
--mllib : default to caffe for backward compatibility can be tensorrt , ncnn
--datatype : datatype for tensorrt , can be fp32[default] or fp16

dd_bench with tensorrt support

---

src/apidata.cc
src/apidata.h
src/backends/caffe/caffelib.cc
src/backends/caffe2/caffe2lib.cc
src/backends/ncnn/ncnnlib.cc
src/backends/tensorrt/tensorrtlib.cc
src/backends/xgb/xgblib.cc
src/csvinputfileconn.h
src/csvtsinputfileconn.cc
src/jsonapi.h
src/mlservice.h
src/services.h
src/supervisedoutputconnector.h
src/utils/fileops.hpp
src/utils/optional.hpp
src/utils/recursive_wrapper.hpp
src/utils/variant.hpp
src/utils/variant_io.hpp
tests/ut-apidata.cc
tests/ut-caffe-mlp.cc
tests/ut-conn.cc

Internal `APIData` structures use [Mapbox variant](https://github.com/mapbox/variant). This is an update to the most recent version, from a many years older version.

updated mapbox variant to v1.1.3

---

src/backends/ncnn/ncnnlib.cc

NCNN update to current master https://github.com/Tencent/ncnn/commit/fb9309e46021f3923e9d8a8be632795b710f256c

updating NCNN option setter

---

src/backends/caffe/caffelib.cc
src/backends/ncnn/ncnnlib.cc
src/csvtsinputfileconn.h
src/inputconnectorstrategy.h

add _timeserie attribute at high level inputconnectorStrategy in order to clean up typeid tests in mllibs

add _timeserie attribute to connectors 

---

clients/python/dd_client.py
src/CMakeLists.txt
src/apidata.cc
src/apidata.h
src/backends/caffe/caffeinputconns.h
src/backends/caffe/caffelib.cc
src/backends/caffe2/caffe2inputconns.h
src/backends/caffe2/caffe2inputimg.cc
src/backends/caffe2/caffe2inputinterface.cc
src/backends/caffe2/caffe2lib.cc
src/backends/dlib/dlibinputconns.h
src/backends/tensorrt/tensorrtinputconns.cc
src/backends/tensorrt/tensorrtinputconns.h
src/backends/tensorrt/tensorrtlib.cc
src/backends/xgb/xgbinputconns.cc
src/backends/xgb/xgbinputconns.h
src/chain.cc
src/chain.h
src/chain_actions.cc
src/chain_actions.h
src/httpjsonapi.cc
src/imginputfileconn.h
src/inputconnectorstrategy.h
src/jsonapi.cc
src/jsonapi.h
src/mlservice.h
src/services.h
src/supervisedoutputconnector.h
src/unsupervisedoutputconnector.h
src/utils/utils.hpp

This PR introduces new `PUT /chain` API calls for chaining up multiple models `/predict` calls with intermediary operators such as `crop` and `filter`.
Typical use-case is an text object detection model followed by an OCR model. The `/chain` API allows to chain the two model predictions in a single call, along with the image in-memory cropping.
This makes multi-models inference much easier to work with. The JSON output reports all model results in a nested manner.
This PR is a work-in-progress.
- Works with Caffe object detection + OCR models + similarity search from neural embeddings
- Nested outputs in JSON format
- Example call from https://www.deepdetect.com/applications/ocr_wild/
```json
{ …
```

Basic multi-models inference with intermediary operators via `/chain` API call

---

docker/cpu-ncnn-pi3/Dockerfile
src/apidata.cc
src/apidata.h
src/chain.h

Was affecting builds on Raspberry 3 & 4.

type fix for variants with long long int

---

src/backends/caffe/caffelib.cc
src/supervisedoutputconnector.h

as body.measure_hist.learning_rate_hist

output learning rate in training json

---

src/backends/caffe/caffelib.cc

see https://github.com/jolibrain/caffe/pull/51 and https://github.com/jolibrain/ddapi/pull/3

dede API for Decoupled wd : adamW and sgdW and amsgradW

---

src/backends/caffe/caffelib.cc

see https://github.com/jolibrain/caffe/pull/52
add a new train parameter : solver.rectified  of type bool

API for rectified flavor of adam and amsgrad

---

src/chain.cc
src/chain.h
src/chain_actions.cc
src/chain_actions.h
src/services.h

This PR adds support for tree-like chained models and actions (#605). This allows for instance an object crop to be served as input to multiple models within a chain. All model results are then integrated into the final JSON response.
API additions:
- `id`: specifies the `id` of an action, otherwise the id is automatically attributed
- `parent_id`: specifies the parent action of a service call within a chain
Example:
```json
{                                                                                                             
"chain": {                                                                                                
"calls": [                                                                                            
{ …
```

Support for tree-structured chains

---

CMakeLists.txt
src/backends/torch/torchlib.cc

* Fix reading mllib parameters
* Fix unnecessary caffe2 rebuild

Fix pytorch backend

---

src/backends/tensorrt/tensorrtlib.cc
src/backends/tensorrt/tensorrtlib.h

TESTED OK
as usual in parameters.mlllib.gpuid

add choice of gpuid in for tensorrt backend

---

src/chain_actions.cc
src/chain_actions.h
src/services.h

This PR allows to log info/warning/errors from within chain actions.
Also, potentially fixes #689

Support for logger from within chain actions

---

src/services.h

Fix potentially empty chain output when first detection service output is empty

---

src/backends/caffe/caffelib.cc
src/backends/caffe/caffelib.h

at test time : 
- remove useless iteration over outputblobs 
- get blob by name 
tested OK on car detection

this PR add some cleanups on caffe detection code 

---

src/backends/caffe/caffelib.cc
src/backends/caffe2/caffe2lib.cc
src/backends/dlib/dliblib.cc
src/backends/ncnn/ncnnlib.cc
src/backends/tensorrt/tensorrtlib.cc
src/backends/tf/tflib.cc
src/backends/torch/torchlib.cc
src/backends/tsne/tsnelib.cc
src/backends/xgb/xgblib.cc
src/outputconnectorstrategy.h
src/supervisedoutputconnector.h
src/unsupervisedoutputconnector.h

add error message in case of unsupervised + !extract  +  fix logging from outputconnectors

fix logging from output connectors + add error message in case of unsupervised output + no extract_layer

---

CMakeLists.txt
README.md
patches/pytorch/pytorch_15_compile.patch
patches/pytorch/pytorch_15_logging.patch

this PR adds support for torch 1.5
changes are :
- slight changes in changes in generic cmakelists.txt : add -std=c++14, -Wl,--no-as-needed , slight changes in torchlib to link, slight change in compile options
- huge changes in logging patch, as many more torch  structures are logging stuff, many more changes are needed in order to log to our spdlog wrapper.

Torch 1.5 integration

---

src/backends/caffe/caffelib.cc

this PR fixes loss used when single target regression is used, previously it was working only with normalized values (or was meant to work only with normalized values, but has never been tested AFAIK)
option is parameters.mlllib.loss    
values are 
- "L1" (smoothL1 with smoothing when error < 10-2) , 
- "L2" (euclidean loss) [default],  
- "sigmoid" (sigmoidcrossentropyloss), to be used only for values between 0 and 1
three options have been tested OK

[FIX] image -> single target regression

---

src/backends/caffe/caffelib.cc

this PR fixes the fix of https://github.com/jolibrain/deepdetect/pull/743/

Fix fix img regression predict

---

src/backends/torch/torchlib.cc
src/backends/torch/torchlib.h
tests/ut-torchapi.cc

this PR add support for : 
- `class_weights` via dd api in torch backend
-  `iteration` value when resuming from an old model
-  best_model behavior : saves best model and record its name in best_model.txt (also removes previously best models because bert models are extremely heavy)

Torchlib production missing features 

---

src/backends/caffe/caffelib.cc
src/backends/caffe/caffelib.h

fixes https://github.com/jolibrain/deepdetect/issues/654

Force cudnn engine for refinedet

---

src/backends/caffe/caffeinputconns.cc
src/backends/caffe/caffelib.cc

This PR allows image multi-target regression. Single target regression was already working fine.

Modifications for image multi target regression

---

CMakeLists.txt
src/CMakeLists.txt

this pr cleanups protoc selection among available version depending on seleted backend at compile time. This simplifies A LOT maintenance of CMakeLists

Cleanup protoc selection

---

src/backends/caffe/caffeinputconns.h

This should fix #761 and #742 and comes in complement to #744

[Fix] Detect lmdb path with sparse models

---

src/apistrategy.h
src/backends/caffe/caffemodel.h
src/backends/caffe2/caffe2model.h
src/backends/dlib/dlibmodel.h
src/backends/ncnn/ncnnmodel.h
src/backends/tensorrt/tensorrtmodel.h
src/backends/tf/tfmodel.h
src/backends/torch/llogging.h
src/backends/xgb/xgbmodel.h
src/chain_actions.h
src/dd_spdlog.h
src/generators/net_caffe.h
src/httpjsonapi.cc
src/inputconnectorstrategy.h
src/mllibstrategy.h
src/mlservice.h
src/outputconnectorstrategy.h
src/services.h

See https://github.com/jolibrain/caffe/pull/74

Fix build with syslog

---

templates/caffe/ssd_300_res_128/deploy.prototxt

fix: ssd_300_res_128 deploy file is missing a quote

---

clients/python/dd_bench.py

New `--json-output FILEPATH` parameter is available for `dd_bench.py` benchmark script, this allows to output benchmark results in a json file.
The output file contains an array similar to the csv ouput, including an item for each batch size with `batch_size`, `mean_processing_time` and `mean_time_per_img` key/values.

feat: add json output to dd_bench.py

---

CMakeLists.txt
README.md
patches/pytorch/pytorch_16_logging.patch

This PR updates patch needed to support torch in dede, particularly at logger level.

support for torch 1.6

---

CMakeLists.txt
src/apidata.h
src/backends/caffe/caffeinputconns.cc
src/backends/caffe/caffeinputconns.h
src/backends/caffe/caffelib.cc
src/backends/caffe/caffelib.h
src/backends/ncnn/caffe2ncnn.cc
src/backends/torch/torchgraphbackend.h
src/backends/torch/torchinputconns.h
src/backends/torch/torchlib.cc
src/backends/torch/torchlib.h
src/backends/xgb/xgbinputconns.cc
src/backends/xgb/xgbinputconns.h
src/backends/xgb/xgblib.h
src/caffegraphinput.h
src/dd_types.h
src/ext/rmustache/mustache.cc
src/generators/net_caffe.cc
src/generators/net_caffe.h
src/httpjsonapi.cc
src/simsearch.h

Pull request for pragma

---

src/generators/net_caffe.h

Remove unnecessary caffe include that prevent build with torch only

fix(dede): Remove unnecessary caffe include

---

CMakeLists.txt
examples/all/sinus/gen.py
src/CMakeLists.txt
src/backends/torch/native/native.h
src/backends/torch/native/native_factory.h
src/backends/torch/native/native_net.h
src/backends/torch/native/templates/nbeats.cc
src/backends/torch/native/templates/nbeats.h
src/backends/torch/torchinputconns.cc
src/backends/torch/torchinputconns.h
src/backends/torch/torchlib.cc
src/backends/torch/torchlib.h
src/backends/torch/torchmodel.cc
src/backends/torch/torchmodel.h
src/generators/net_caffe.h
tests/ut-torchapi.cc

https://github.com/philipperemy/n-beats/

feat(torch) : Native torch C++ model interface + NBEATS architecture implementation for time-series 

---

src/CMakeLists.txt
src/backends/caffe/caffelib.cc
src/backends/dlib/dliblib.cc
src/backends/ncnn/ncnnlib.cc
src/backends/tensorrt/tensorrtinputconns.cc
src/backends/tensorrt/tensorrtinputconns.h
src/backends/tensorrt/tensorrtlib.cc
src/backends/tf/tflib.cc
src/backends/torch/torchlib.cc
src/backends/xgb/xgblib.cc
src/jsonapi.cc
src/mllibstrategy.h
src/mlservice.h
src/service_stats.cc
src/service_stats.h
tests/ut-jsonapi.cc
tests/ut-torchapi.cc

the initial version returns:
inference_count
predict_success
predict_failure
predict_count
avg_batch_size
avg_predict_duration
avg_transform_duration

feat(stats): added service statistics mechanism

---

src/backends/torch/native/templates/nbeats.cc

this PR fixes nbeats so that it implements paper version and not code version

Fix(nbeats): implement  paper trend and seasonality

---

CMakeLists.txt

Update to TensorRT backend for version 7+.

chore: bump TensorRT version to 20.09

---

src/backends/torch/native/native_factory.h
src/backends/torch/native/templates/nbeats.h

this PR allows user not to give template_param to native modules, allowing default from module to be used

fix(native) fix no template param, fallback to default

---

src/backends/torch/native/native_net.h
src/backends/torch/native/templates/nbeats.cc
src/backends/torch/native/templates/nbeats.h
src/backends/torch/torchgraphbackend.cc
src/backends/torch/torchgraphbackend.h
src/backends/torch/torchlib.cc
src/backends/torch/torchlib.h
tests/ut-graph.cc
tests/ut-torchapi.cc

This PR add extract_layer feature for torchlib based networks (ie native, graph and , to some extent, to _traced)

Torch extract layer + NBEATS layer extract

---

src/csvinputfileconn.cc
src/csvinputfileconn.h
src/csvtsinputfileconn.cc
src/csvtsinputfileconn.h

chore: in-code function documentation for csv and csvts connectors

fix: fix split_data in csvts connector

---

CHANGELOG.md
ci/Jenkinsfile.docker
package.json

Pull request for master

---

CMakeLists.txt
build.sh
patches/pytorch/pytorch_16_fatbin.patch

chore(docker): remove old CUDA architecture

---

build.sh
docker/check-dede-deps.sh
docker/cpu.Dockerfile
docker/get_libs.sh
docker/gpu.Dockerfile
docker/gpu_tensorrt.Dockerfile
tools/build-docker-images.sh

Pull request for push-ceres

---

ci/Jenkinsfile.dataset-cache
ci/Jenkinsfile.docker
ci/Jenkinsfile.pytorch-cache
ci/Jenkinsfile.unittests

ci: always show env and don't fail for rocketchat

---

ci/Jenkinsfile.unittests
tests/CMakeLists.txt

This make cmake fail if a dataset can't be downloaded or uncompressed.

build: rework examples download

---

src/backends/torch/torchinputconns.cc
src/imginputfileconn.h

Put `DDimg` parameters initialization and image preprocessing in functions.

refactor(image): Remove duplicate code in ImgInputConnector

---

CMakeLists.txt
build.sh
dd_config.h.in
docker/cpu.Dockerfile
src/dd_config.h.in
src/deepdetect.cc
src/githash.h.in
src/jsonapi.cc
tools/build-docker-images.sh

feat(api): add versions and compile flags to /info

---

docs/api.md
src/CMakeLists.txt
src/backends/torch/native/native_factory.cc
src/backends/torch/native/native_factory.h
src/backends/torch/native/native_net.h
src/backends/torch/optim/ranger.cc
src/backends/torch/optim/ranger.h
src/backends/torch/torchUtils.h
src/backends/torch/torchlib.cc
src/backends/torch/torchlib.h
src/backends/torch/torchmodule.cc
src/backends/torch/torchmodule.h
src/backends/torch/torchsolver.cc
src/backends/torch/torchsolver.h
src/backends/torch/torchutils.cc
tests/ut-torchapi.cc

this PR adds ranger + extensions as native torch optimizer (ie coded in c++)
ranger is rectified ADAM  + lookahead
extensions added are : adabelief and centralized gradient
see docs/api and unit test for examples

torch ranger 

---

ci/Jenkinsfile.unittests
clients/python/.gitignore
clients/python/README.md
clients/python/dd_client/__init__.py
clients/python/dd_client/bench.py
clients/python/setup.cfg
clients/python/setup.py
clients/python/tox.ini

This auto format code with black and fix all pep8 issues
Add tox to autoformat/check pep8/run tests.
The first test currently is only to load dd_bench to check the
python syntax.
The makes the python package python 2.7 and >= 3.6 compatible.

chore(python): introduce some minimal code rules

---

src/csvtsinputfileconn.cc
tests/ut-conn.cc

throw a nice exception instead

fix(timeseries): do not segfault if no valid files in train/test dir

---

src/backends/torch/torchinputconns.cc
src/backends/torch/torchinputconns.h
src/backends/torch/torchlib.cc
src/backends/torch/torchlib.h
src/backends/torch/torchmodel.h
src/backends/torch/torchmodule.cc
src/backends/torch/torchmodule.h
src/backends/torch/torchsolver.cc
src/backends/torch/torchsolver.h
src/backends/torch/torchutils.cc
src/backends/torch/torchutils.h

this PR adds doc to methods and attributes along with some minor cleanups

chore(torch): add doc + minor cleanups

---

src/backends/torch/optim/ranger.cc
src/backends/torch/optim/ranger.h

not sure if it fixes anything, but this version is more correct than previous one

fix(torch): correctly implements range state comparison

---

docs/api.md
src/backends/torch/optim/ranger.cc
src/backends/torch/optim/ranger.h
src/backends/torch/torchsolver.cc
src/backends/torch/torchsolver.h
tests/ut-torchapi.cc

before this PR, only RANGER was clipping gradient if asked for, we now allow for clipping gradients (both to values and to norm) for all torch optimizers

feat(torch): clip gradient options for all optimizers

---

docs/api.md

Was breaking rendering on https://www.deepdetect.com/api

fix: broken API doc formatting

---

CMakeLists.txt

ci: add missing LD_LIBRARY_PATH

---

.mergify.yml

This change has been made by @sileht from https://mergify.io config editor.

ci: configuration update

---

tests/CMakeLists.txt

currently is BUILD_TESTS is set and gtest not installed, we continue
with just a warning lost in the middle of the logs.
This change makes this case fatal.

build: BUILD_TESTS must required gtest

---

src/backends/torch/torchgraphbackend.cc
src/backends/torch/torchgraphbackend.h
src/backends/torch/torchinputconns.cc
src/backends/torch/torchmodule.cc

this PR adds a lot of very usefull log for processing csv timesries in torch:
- it shows data / columns as found by the connector : input, labels ....
- it shows input dims needed by the loaded model (if it does not match with above torch with throw little after that)

feat(torch/timeseries): log much more info on data

---

tests/ut-torchapi.cc

this PR loosens a threshold on ut on learning, which failed quite often

fix(torch): loosen ut test

---

src/backends/torch/native/templates/vit.cc
src/backends/torch/native/templates/vit.h
tests/ut-torchapi.cc

This PR adds multi-GPU support to the ViT native torch model.

feat: vision transformer (ViT) multi-gpu with torch

---

CMakeLists.txt
cmake/FindCUDNN.cmake
src/dd_config.h.in

This will allow to support custom directory for CUDNN and get the CUDNN
version.

feat: add cudnn cmake find package

---

.mergify.yml

This reverts commit 2670bf4b0d0eb414d1f52fad461baf731067715b.

Revert "ci: simplify mergify rules"

---

CMakeLists.txt

feat: use jolibrain fork of faiss

---

ci/Jenkinsfile.docker
ci/build-docker-images.sh

ci: test docker image start and work

---

src/backends/ncnn/ncnnlib.cc
src/backends/ncnn/ncnnmodel.cc
tests/CMakeLists.txt
tests/ut-ncnnapi.cc

fix: NCNN best parameter for classification models

---

src/backends/torch/native/templates/vit.cc

Weights are available from https://github.com/facebookresearch/deit

ml: torch ViT small and tiny models as in https://arxiv.org/abs/201212877

---

src/backends/ncnn/ncnninputconns.h
src/backends/ncnn/ncnnlib.cc
tests/ut-ncnnapi.cc

This adds the ability to pass multiple images to NCNN with image models. Time-series model are still using batch size of 1.

feat: support for batches for NCNN image models

---

src/backends/torch/torchdataset.cc
src/backends/torch/torchdataset.h
src/backends/torch/torchinputconns.cc
src/backends/torch/torchinputconns.h

Torchdataset were shuffled randomely with seed always taken from current time.

fix(torch): set seed of torchdataset during training

---

docs/api.md
src/backends/torch/torchlib.cc
src/backends/torch/torchmodule.cc
src/backends/torch/torchmodule.h

Example usage:
- From https://github.com/openai/CLIP, get OpenAI CLIP model from https://openaipublic.azureedge.net/clip/models/40d365715913c9da98579312b702a82c18be219cc2a73407c4526f58eba950af/ViT-B-32.pt  and put it into a directory
- Create service:
```bash
curl -X PUT http://localhost:8080/services/testclip -d '                                             
{"mllib":"torch","description":"image","type":"supervised","model":{"repository":"/path/to/model\
s/clip/"},"parameters":{"input":{"connector":"image","width":224,"height":224},"mllib":{"gpu":true,"gpuid":0}}}                                                                                       
'       
```
- Inference on an image:
```bash
curl -X POST http://localhost:8080/predict -d ' …
```

feat: running custom methods from jit models

---

docs/api.md
src/backends/torch/native/templates/vit.cc
src/backends/torch/native/templates/vit.h
tests/ut-torchapi.cc

From https://arxiv.org/abs/201211747v2. Will provide some accuracy metrics on simple image classification datasets for ViT tiny.

feat(ml): ViT support for Realformer

---

docs/api.md
src/backends/caffe/caffeinputconns.cc
src/csvinputfileconn.cc
src/csvinputfileconn.h
src/utils/csv_parser.hpp

Two new CSV parser features:
- new parser that supports quotes around strings, from https://github.com/AriaFallah/csv-parser
- support for non integer labels in CSV files, with automatic corresp file creation, like for other data input connectors.

feat: CSV parser support for quotes and string labels

---

src/csvtsinputfileconn.cc
src/csvtsinputfileconn.h
tests/ut-torchapi.cc

fix(csvts): read from memory

---

clients/python/setup.cfg

Changing project name as suggested here https://github.com/jolibrain/dd_platform_docker/pull/47

fix(client): Change python package name to dd_client

---

docs/api.md
src/CMakeLists.txt
src/backends/torch/native/native_factory.cc
src/backends/torch/native/native_factory.h
src/backends/torch/native/templates/ttransformer.cc
src/backends/torch/native/templates/ttransformer.h
src/backends/torch/native/templates/ttransformer/positionalenc.cc
src/backends/torch/native/templates/ttransformer/positionalenc.h
src/backends/torch/native/templates/ttransformer/tdecoder.cc
src/backends/torch/native/templates/ttransformer/tdecoder.h
src/backends/torch/native/templates/ttransformer/tembedder.cc
src/backends/torch/native/templates/ttransformer/tembedder.h
src/backends/torch/native/templates/ttransformer/tencoder.cc
src/backends/torch/native/templates/ttransformer/tencoder.h
src/backends/torch/native/templates/ttransformer/ttypes.h
src/backends/torch/torchmodule.cc
tests/ut-torchapi.cc

this PR adds support for tranformer for timeseries
some features : most parameters exposed in API
some missing features : decoder not yet implemented ; autoregressive not yet implemented , only encoder/nbeats style prediction ATM , no pretrain ATM  
Mostly inspired from https://arxiv.org/abs/2010.02803

temporal transformer

---

ci/Jenkinsfile.docker
docker/cpu.Dockerfile
docker/gpu.Dockerfile
docker/gpu_tensorrt.Dockerfile

tensorrt base image have a broken pip3 installation.
This fixes it

fix(docker): ensure pip3 is working on all images

---

src/backends/torch/torchinputconns.cc
src/backends/torch/torchinputconns.h
src/backends/torch/torchlib.cc
src/backends/torch/torchlib.h
tests/CMakeLists.txt
tests/ut-torchapi.cc
tools/torch/trace_torchvision.py

Supports detection models that are available in torchvision: Faster
RCNN, RetinaNet

feat(torch): add inference for torch detection models

---

CMakeLists.txt
src/backends/tensorrt/tensorrtlib.cc
src/backends/tensorrt/tensorrtlib.h

seems to fix https://github.com/jolibrain/deepdetect/issues/1260

fix(TensorRT): fix some memory fragmentation weirdness in trt backend

---

CMakeLists.txt
patches/pytorch/pytorch_18_string_view.patch

See https://github.com/pytorch/pytorch/pull/57322/

fix(build): torch 1.8 with cuda 11.3 string_view patch

---

tools/torch/trace_torchvision.py

now that randperm bug has been fixed in torchvision 0.10, we don't need a patched torchvision anymore and we can use the default

chore: use default torchvision for trace_torchvision

---

CMakeLists.txt

(as cudnn is now on by default)

fix(cpu): auto switch off cudnn in case of cpu_only

---

CMakeLists.txt
src/backends/dlib/dlib_actions.cpp
src/backends/dlib/dlib_actions.h
src/backends/tensorrt/tensorrtinputconns.cc
src/backends/tensorrt/tensorrtinputconns.h
src/backends/tensorrt/tensorrtlib.cc
src/backends/tensorrt/tensorrtlib.h
src/backends/torch/torchdataset.cc
src/chain.h
src/chain_actions.cc
src/chain_actions.h
src/dto/chain.hpp
src/dto/input_connector.hpp
src/dto/output_connector.hpp
src/dto/service_predict.hpp
src/imginputfileconn.h
src/inputconnectorstrategy.h
src/mlmodel.h
src/services.h
src/supervisedoutputconnector.h
src/unsupervisedoutputconnector.h

Improved performances (0 copy, no expensive structured data conversion)
Can only be used when linking to deepdetect for now

feat: chain uses dto end to end

---

src/backends/torch/torchdataset.cc
src/backends/torch/torchdataset.h
src/backends/torch/torchinputconns.cc
src/backends/torch/torchinputconns.h
src/backends/torch/torchlib.cc
src/backends/torch/torchloss.cc
src/backends/torch/torchloss.h
tests/CMakeLists.txt
tests/ut-torchapi.cc

This PR brings segmentation model training to the torch backend.

feat: training segmentation models with torch backend

---

src/backends/tensorrt/tensorrtlib.cc
src/backends/tensorrt/tensorrtlib.h
src/dto/output_connector.hpp
src/imginputfileconn.h
src/utils/bbox.hpp
tests/CMakeLists.txt
tests/ut-tensorrtapi.cc
tools/torch/trace_yolox.py

feat: add yolox onnx export and trt support

---

src/backends/torch/torchdataaug.cc
src/backends/torch/torchdataaug.h
src/backends/torch/torchlib.cc
tests/ut-torchapi.cc

This PR adds noise image transforms. Activated through API with 
```json
"mllib":{"noise":{"prob":0.01}}
```

feat: noise image data augmentation for training with torch backend

---

src/backends/torch/torchdataaug.cc
tests/ut-torchapi.cc

Object detection training: cutout applied to image, and bboxes left unchanged.

feat(ml): activate cutout for object detector training with torch backend

---

CMakeLists.txt

https://github.com/pytorch/pytorch/releases/tag/v1.10.1
https://github.com/pytorch/vision/releases/tag/v0.11.2

chore: update to torch 1.10.1

---

demo/segmentation/segment_sliding.py

Script useful as an example of how to process large images. Demo applies to segmentation output maps.

feat: segmentation of large images with sliding window, example Python script

---

src/chain_actions.cc
src/chain_actions.h

Example
```cpp
class SayHelloAction : public ChainAction                                                                                                                                                                
{                                                                                                                                                                                                        
public:                                                                                                                                                                                                  
SayHelloAction(oatpp::Object<DTO::ChainCall> call_dto, …
```

feat(chain): allow chain custom actions

---

src/backends/caffe/caffeinputconns.cc

Fixes #1399 
Tested with external script.

fix: caffe object detector training requires test set

---

src/supervisedoutputconnector.h

this PR fixes normalization of MAP when using detection with torch backend
Details: with caffe backend, no empty detection were passed to supervisedoutput connector, but with torch backend this can happen as results are sorted by class, so if a class has no instance in an image, an empty vector is given to supervisedoutput connector. this PR normalizes MAPs with number of non empty detections

Fix map with torch

---

src/backends/torch/torchlib.cc

fix: torch MaP with bboxes

---

src/backends/tensorrt/protoUtils.cc
src/backends/tensorrt/protoUtils.h
src/backends/tensorrt/tensorrtlib.cc
src/backends/tensorrt/tensorrtlib.h
src/dto/output_connector.hpp

Adds `predict.output.top_k` control for object detection with tensorRT

feat: tensorrt object detector top_k control

---

src/backends/torch/torchmodel.cc
tests/ut-torchapi.cc

Fixes a bug introduced by earlier refactoring for publishing torch models with random cropping as data augmentation. 
Adds the relevant unit test as well.

fix: cropped model input size when publishing torch models + tests

---

src/backends/torch/torchlib.cc

fix: torch best model better or equal

---

CMakeLists.txt
ci/Jenkinsfile.prebuilt-cache
ci/Jenkinsfile.unittests

this PR makes cache work during ci

make cache work

---

src/backends/torch/torchdataaug.h
tests/ut-torchapi.cc

fix: cutout and crops in data augmentation of torch models

---

src/CMakeLists.txt
src/backends/torch/native/templates/crnn.cc
src/backends/torch/native/templates/crnn.hpp
src/backends/torch/torchdataset.cc
src/backends/torch/torchdataset.h
src/backends/torch/torchinputconns.cc
src/backends/torch/torchinputconns.h
src/backends/torch/torchlib.cc
src/backends/torch/torchlib.h
src/backends/torch/torchloss.cc
src/backends/torch/torchloss.h
src/backends/torch/torchmodel.cc
src/backends/torch/torchmodel.h
src/backends/torch/torchmodule.cc
src/backends/torch/torchmodule.h
src/backends/torch/torchutils.cc
src/dto/mllib.hpp
src/inputconnectorstrategy.h
tests/CMakeLists.txt
tests/ut-torchapi.cc
tools/torch/trace_torchvision.py

TODO:
```bash
cd tools/torch/
./trace_torchvision.py resnet50 --print-extract
./trace_torchvision.py -v resnet50 --extract layer2
```
```bash
curl -X POST "http://10.10.77.105:8500/services/ocr_test" -d '{
"description": "OCR example",
"type": "supervised",
"input": {
"width": 112,
"height": 32,
"db": true,
"ctc": true
},
"mllib": {
"template": "crnn",
"finetuning": true,
"gpu": true,
"gpuid": 0
},
"output": {
"store_config": true
}
},
"model": {
"repository": "/opt/platform/models/private/ocr_test/"
}
}'
```
```bash
curl -X POST "http://10.10.77.105:8500/train/" -d '{
"service": "ocr_test",
"async": true,
"input": {
"shuffle": true,
"db": true,
"ctc":true
},
"mllib": {
"gpu": true,
"gpuid": 0,
"resume": false, …
```

feat(torch): ocr model training and inference

---

CMakeLists.txt
src/backends/dlib/dlib_actions.cpp
src/backends/dlib/dlib_actions.h
src/backends/dlib/dliblib.cc
src/jsonapi.cc

Update to fix some dlib regressions, and update the dlib version (which also fixes one new issue with opencv4).
This should be merged after https://github.com/jolibrain/deepdetect/pull/1448.

Dlib version update and regression fixes

---

src/backends/torch/torchlib.cc

Fixes https://github.com/jolibrain/deepdetect/issues/1456

Fix torch model behavior with best: -1

---

CMakeLists.txt

fix(oatpp): oatpp-zlib memory leak

---

ci/Jenkinsfile.unittests
clients/python/dd_client/__init__.py
clients/python/tox.ini

Alternate proposition for #1477

chore: raw image support in cv2 format for dd_client

---

src/backends/torch/torchdataset.cc
src/backends/torch/torchdataset.h
src/backends/torch/torchinputconns.cc
tests/ut-torchapi.cc

plus cleanup around image_to_tensor

feat(torch): allow data augmentation w/o db

---

src/backends/torch/torchdataset.cc

Thanks @fantes for the heads up!

fix(torch): avoid race condition when building alphabet

---

src/backends/torch/torchdataset.cc
tools/torch/trace_yolox.py

(includes a minor cosmetic change to trace_yolox.py)

fix(torch): data augmentation handle dummy bboxes correctly

---

src/dto/info.hpp
src/mlservice.h
src/utils/oatpp.cc
tests/ut-oatpp.cc

Forgot this in last commit, it breaks the platform

fix(api): re-add parameters in info call

---

src/backends/torch/torchutils.cc
src/backends/torch/torchutils.h

it can be helpful for debugging, to print the images as received by the network

chore: add function to convert tensor to images

---

src/http/controller.hpp
src/utils/utils.hpp
tests/ut-oatpp.cc

fix: support boolean value for service info parameters

---

src/backends/tensorrt/tensorrtlib.cc
src/services.h
tests/ut-chain.cc

was returning empty `predictions` vector instead of predictions with empty `classes` vector

fix(chain): empty predictions were too empty

---

tests/ut_python/ut_tools_torch_yolox.py

ci:skip-tests because this test is not ran during CI (YOLOX is not installed)

test: add training and test checks in trace_yolox tests

---

tools/torch/trace_rtdetrv2.py

new options:
`--num_queries` to change `num_queries` and `num_top_queries`, `num_denoising` is set to 1/3 of this value
`--img_width` & `--img_height` to change the `eval_spatial_size`
`--nms_threshold` to add an optional NMS after inference with the specified IoU threshold
empty bboxes are now handled as well, but still fail if the whole batch contains images without bboxes
maybe related: https://github.com/pytorch/pytorch/issues/144965

feat: more RT-DETRv2 options
